### ISSUE TITLE
TLS timeout leads to nil pointer error during image pull

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1079]
```
time="2018-10-05T03:25:04Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]docker.io/centos/ruby-22-centos7:latest\""
Registry for "centos/ruby-22-centos7" is not present in the registries configuration, assuming it is secure.
time="2018-10-05T03:25:04Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]docker.io/centos/ruby-22-centos7:latest\""
time="2018-10-05T03:25:04Z" level=debug msg="copying \"docker://centos/ruby-22-centos7\" to \"docker.io/centos/ruby-22-centos7:latest\""
time="2018-10-05T03:25:04Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
time="2018-10-05T03:25:04Z" level=debug msg=" No signature storage configuration found for docker.io/centos/ruby-22-centos7:latest"
time="2018-10-05T03:25:04Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io"
time="2018-10-05T03:25:04Z" level=debug msg="GET https://registry-1.docker.io/v2/"
time="2018-10-05T03:25:16Z" level=debug msg="Ping https://registry-1.docker.io/v2/ err Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout (&url.Error{Op:\"Get\", URL:\"https://registry-1.docker.io/v2/\", Err:http.tlsHandshakeTimeoutError{}})"
time="2018-10-05T03:25:16Z" level=debug msg="GET https://registry-1.docker.io/v1/_ping"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12ec9d5]

goroutine 1 [running]:
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties.func2(0x17f8abe, 0x5, 0x181f800)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:545 +0x205
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties(0xc420818300, 0x19c7740, 0xc4200b8018, 0x25, 0xc4206fd380)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:556 +0x1ab
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).makeRequest(0xc420818300, 0x19c7740, 0xc4200b8018, 0x17f7629, 0x3, 0xc4204c5f20, 0x2b, 0xc420b1e688, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:373 +0x5a
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).fetchManifest(0xc420765dc0, 0x19c7740, 0xc4200b8018, 0x17f97e2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:92 +0x2b7
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).ensureManifestIsLoaded(0xc420765dc0, 0x19c7740, 0xc4200b8018, 0x0, 0x2682a00)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:124 +0xa0
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).GetManifest(0xc420765dc0, 0x19c7740, 0xc4200b8018, 0x0, 0xc420964980, 0xc4209649c8, 0x412e09, 0xc4209ae5a0, 0x30, 0xc4209649e8, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:81 +0x57
github.com/openshift/builder/vendor/github.com/containers/image/image.(*UnparsedImage).Manifest(0xc420092cc0, 0x19c7740, 0xc4200b8018, 0x1775e80, 0xc420964a18, 0x413658, 0x60, 0x16fab00, 0x1775e01, 0xc420092cc0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/image/unparsed.go:46 +0xd7
github.com/openshift/builder/vendor/github.com/containers/image/copy.isMultiImage(0x19c7740, 0xc4200b8018, 0x19b8b80, 0xc420092cc0, 0xc420964c28, 0xc420765dc0, 0x0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/manifest.go:116 +0x49
github.com/openshift/builder/vendor/github.com/containers/image/copy.Image(0x19c7740, 0xc4200b8018, 0xc420729ae0, 0x19d8080, 0xc420092ba0, 0x19d83e0, 0xc4203166a0, 0xc420b1ee08, 0x0, 0x0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/copy.go:152 +0x340
github.com/openshift/builder/vendor/github.com/containers/buildah.pullImage(0x19c7740, 0xc4200b8018, 0x19f0e60, 0xc42032f0e0, 0xc420457a60, 0x1f, 0x0, 0x0, 0x19a8880, 0xc4200bc010, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/pull.go:193 +0x49c
github.com/openshift/builder/vendor/github.com/containers/buildah.Pull(0x19c7740, 0xc4200b8018, 0xc420457a60, 0x1f, 0x0, 0x0, 0x19a8880, 0xc4200bc010, 0x19f0e60, 0xc42032f0e0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/pull.go:141 +0x163
github.com/openshift/builder/pkg/build/builder.pullDaemonlessImage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/pkg/build/builder/daemonless.go:88 +0x881
github.com/openshift/builder/pkg/build/builder.(*DaemonlessClient).PullImage(0xc4203d4160, 0xc420524ce5, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/pkg/build/builder/daemonless.go:556 +0x107
```

This should be either retried or reported as a failure, not cause a nil pointer failure.

**Comment by nalind** [comment]
This should be fixed by #1082, closing.
