### ISSUE TITLE
nil pointer error when image can't be found

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1105]
it looks like ultimately a connection reset lead to the nil ptr error:
```
time="2018-10-16T14:47:26Z" level=debug msg="Ping https://registry.access.redhat.com/v2/ err Get https://registry.access.redhat.com/v2/: read tcp 172.16.6.40:33050->209.132.182.63:443: read: connection reset by peer (&url.Error{Op:\"Get\", URL:\"https://registry.access.redhat.com/v2/\", Err:(*net.OpError)(0xc4203e7680)})"
time="2018-10-16T14:47:26Z" level=debug msg="GET https://registry.access.redhat.com/v1/_ping"
panic: runtime error: invalid memory address or nil pointer dereference
```

I would expect this to instead fail gracefully with a clear "failure to pull image" error.

full build log:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-4.0/833#featurebuilds-multi-stage-image-builds-should-succeed-conformance-suiteopenshiftconformanceparallelminimal

```
time="2018-10-16T14:47:21Z" level=debug msg="reading local Dockerfile \"/tmp/build/inputs/Dockerfile\""
time="2018-10-16T14:47:21Z" level=debug msg="FROM \"centos:7 AS test\""
STEP 1: FROM centos:7 AS test
time="2018-10-16T14:47:21Z" level=debug msg="error parsing image name \"localhost/centos:7\" as given, trying with transport \"docker://\": Invalid image name \"localhost/centos:7\", unknown transport \"localhost/centos\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="reference \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]localhost/centos:7\" does not resolve to an image ID"
time="2018-10-16T14:47:21Z" level=debug msg="error parsing image name \"localhost/centos:7\", trying with transport \"docker://\": Invalid image name \"localhost/centos:7\", unknown transport \"localhost/centos\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed image name \"docker://localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="registry \"localhost\" is not listed in registries configuration \"/etc/containers/registries.conf\", assuming it's not blocked"
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="copying \"docker://localhost/centos:7\" to \"localhost/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="registry \"localhost\" is not listed in registries configuration \"/etc/containers/registries.conf\", assuming it's secure"
time="2018-10-16T14:47:21Z" level=debug msg="registry \"localhost\" is not listed in registries configuration \"/etc/containers/registries.conf\", assuming it's secure"
time="2018-10-16T14:47:21Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
time="2018-10-16T14:47:21Z" level=debug msg=" No signature storage configuration found for localhost/centos:7"
time="2018-10-16T14:47:21Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/localhost"
time="2018-10-16T14:47:21Z" level=debug msg="GET https://localhost/v2/"
time="2018-10-16T14:47:21Z" level=debug msg="Ping https://localhost/v2/ err Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused (&url.Error{Op:\"Get\", URL:\"https://localhost/v2/\", Err:(*net.OpError)(0xc4200bcd70)})"
time="2018-10-16T14:47:21Z" level=debug msg="GET https://localhost/v1/_ping"
time="2018-10-16T14:47:21Z" level=debug msg="Ping https://localhost/v1/_ping err Get https://localhost/v1/_ping: dial tcp [::1]:443: connect: connection refused (&url.Error{Op:\"Get\", URL:\"https://localhost/v1/_ping\", Err:(*net.OpError)(0xc4200bd220)})"
time="2018-10-16T14:47:21Z" level=debug msg="error pulling image \"localhost/centos:7\": Error determining manifest MIME type for docker://localhost/centos:7: pinging docker registry returned: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused"
time="2018-10-16T14:47:21Z" level=debug msg="unable to pull and read image \"localhost/centos:7\": Error determining manifest MIME type for docker://localhost/centos:7: pinging docker registry returned: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused"
time="2018-10-16T14:47:21Z" level=debug msg="error parsing image name \"quay.io/centos:7\" as given, trying with transport \"docker://\": Invalid image name \"quay.io/centos:7\", unknown transport \"quay.io/centos\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="reference \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]quay.io/centos:7\" does not resolve to an image ID"
time="2018-10-16T14:47:21Z" level=debug msg="error parsing image name \"quay.io/centos:7\", trying with transport \"docker://\": Invalid image name \"quay.io/centos:7\", unknown transport \"quay.io/centos\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed image name \"docker://quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="registry \"quay.io\" is not marked as blocked in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="copying \"docker://quay.io/centos:7\" to \"quay.io/centos:7\""
time="2018-10-16T14:47:21Z" level=debug msg="registry \"quay.io\" is not marked insecure in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:21Z" level=debug msg="registry \"quay.io\" is not marked insecure in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:21Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
time="2018-10-16T14:47:21Z" level=debug msg=" No signature storage configuration found for quay.io/centos:7"
time="2018-10-16T14:47:21Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.io"
time="2018-10-16T14:47:21Z" level=debug msg="GET https://quay.io/v2/"
time="2018-10-16T14:47:21Z" level=debug msg="Ping https://quay.io/v2/ status 401"
time="2018-10-16T14:47:21Z" level=debug msg="GET https://quay.io/v2/auth?scope=repository%3Acentos%3Apull&service=quay.io"
time="2018-10-16T14:47:21Z" level=debug msg="Increasing token expiration to: 60 seconds"
time="2018-10-16T14:47:21Z" level=debug msg="GET https://quay.io/v2/centos/manifests/7"
time="2018-10-16T14:47:22Z" level=debug msg="error pulling image \"quay.io/centos:7\": Error determining manifest MIME type for docker://quay.io/centos:7: Error reading manifest 7 in quay.io/centos: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 3.2 Final//EN\\\">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\\n\""
time="2018-10-16T14:47:22Z" level=debug msg="unable to pull and read image \"quay.io/centos:7\": Error determining manifest MIME type for docker://quay.io/centos:7: Error reading manifest 7 in quay.io/centos: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 3.2 Final//EN\\\">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\\n\""
time="2018-10-16T14:47:22Z" level=debug msg="error parsing image name \"registry.access.redhat.com/centos:7\" as given, trying with transport \"docker://\": Invalid image name \"registry.access.redhat.com/centos:7\", unknown transport \"registry.access.redhat.com/centos\""
time="2018-10-16T14:47:22Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="reference \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]registry.access.redhat.com/centos:7\" does not resolve to an image ID"
time="2018-10-16T14:47:22Z" level=debug msg="error parsing image name \"registry.access.redhat.com/centos:7\", trying with transport \"docker://\": Invalid image name \"registry.access.redhat.com/centos:7\", unknown transport \"registry.access.redhat.com/centos\""
time="2018-10-16T14:47:22Z" level=debug msg="parsed image name \"docker://registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="registry \"registry.access.redhat.com\" is not marked as blocked in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:22Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="copying \"docker://registry.access.redhat.com/centos:7\" to \"registry.access.redhat.com/centos:7\""
time="2018-10-16T14:47:22Z" level=debug msg="registry \"registry.access.redhat.com\" is not marked insecure in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:22Z" level=debug msg="registry \"registry.access.redhat.com\" is not marked insecure in registries configuration \"/etc/containers/registries.conf\""
time="2018-10-16T14:47:22Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
time="2018-10-16T14:47:22Z" level=debug msg=" No signature storage configuration found for registry.access.redhat.com/centos:7"
time="2018-10-16T14:47:22Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.access.redhat.com"
time="2018-10-16T14:47:22Z" level=debug msg="GET https://registry.access.redhat.com/v2/"
time="2018-10-16T14:47:26Z" level=debug msg="Ping https://registry.access.redhat.com/v2/ err Get https://registry.access.redhat.com/v2/: read tcp 172.16.6.40:33050->209.132.182.63:443: read: connection reset by peer (&url.Error{Op:\"Get\", URL:\"https://registry.access.redhat.com/v2/\", Err:(*net.OpError)(0xc4203e7680)})"
time="2018-10-16T14:47:26Z" level=debug msg="GET https://registry.access.redhat.com/v1/_ping"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12eed85]

goroutine 1 [running]:
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties.func2(0x17feedd, 0x5, 0x1825e00)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:545 +0x205
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties(0xc420a7a540, 0x19d0440, 0xc420591020, 0x15, 0xc4200e0100)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:556 +0x1ab
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).makeRequest(0xc420a7a540, 0x19d0440, 0xc420591020, 0x17fda4c, 0x3, 0xc420804b00, 0x16, 0xc4211e4548, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:373 +0x5a
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).fetchManifest(0xc4206c8880, 0x19d0440, 0xc420591020, 0xc420b61d92, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:92 +0x2b7
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).ensureManifestIsLoaded(0xc4206c8880, 0x19d0440, 0xc420591020, 0x0, 0xc4203b0000)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:124 +0xa0
github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).GetManifest(0xc4206c8880, 0x19d0440, 0xc420591020, 0x0, 0xc4211e4840, 0xc4211e4888, 0x412ea9, 0xc420612150, 0x30, 0xc4211e48a8, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:81 +0x57
github.com/openshift/builder/vendor/github.com/containers/image/image.(*UnparsedImage).Manifest(0xc420593500, 0x19d0440, 0xc420591020, 0x177c000, 0xc4211e48d8, 0x4136f8, 0x60, 0x1700920, 0x177c001, 0xc420593500)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/image/unparsed.go:46 +0xd7
github.com/openshift/builder/vendor/github.com/containers/image/copy.isMultiImage(0x19d0440, 0xc420591020, 0x19c1900, 0xc420593500, 0xc4211e4ae8, 0xc4206c8880, 0x0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/manifest.go:116 +0x49
github.com/openshift/builder/vendor/github.com/containers/image/copy.Image(0x19d0440, 0xc420591020, 0xc420aebb20, 0x19e0d00, 0xc420592e40, 0x19e1060, 0xc420b2f4f0, 0xc420593320, 0x0, 0x0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/copy.go:152 +0x340
github.com/openshift/builder/vendor/github.com/containers/buildah.pullImage(0x19d0440, 0xc420591020, 0x19f9ae0, 0xc420200120, 0xc420aded20, 0x23, 0x0, 0x0, 0x19b1640, 0xc4200ba008, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/pull.go:203 +0x6c2
github.com/openshift/builder/vendor/github.com/containers/buildah.pullAndFindImage(0x19d0440, 0xc420591020, 0x19f9ae0, 0xc420200120, 0xc420aded20, 0x23, 0xc4207c6e70, 0xc4207f8a45, 0x8, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:43 +0x14d
github.com/openshift/builder/vendor/github.com/containers/buildah.resolveImage(0x19d0440, 0xc420591020, 0xc42061ac80, 0x19f9ae0, 0xc420200120, 0xc4207c6e70, 0xc4207f8a45, 0x8, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:194 +0xde2
github.com/openshift/builder/vendor/github.com/containers/buildah.newBuilder(0x19d0440, 0xc420591020, 0x19f9ae0, 0xc420200120, 0xc4207c6e70, 0xc4207f8a45, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:250 +0x17e1
github.com/openshift/builder/vendor/github.com/containers/buildah.NewBuilder(0x19d0440, 0xc420591020, 0x19f9ae0, 0xc420200120, 0xc4207c6e70, 0xc4207f8a45, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/buildah.go:401 +0x97
github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Prepare(0xc4203ee000, 0x19d0440, 0xc420591020, 0x0, 0xc4207f8a51, 0x4, 0xc420357340, 0xc4206df490, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:674 +0x3c2
github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Build(0xc42014edc0, 0x19d0440, 0xc420591020, 0xc4200bcaa0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:1192 +0x1f2
github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x19d0440, 0xc420591020, 0x19f9ae0, 0xc420200120, 0xc420805ee0, 0x11, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:1335 +0xfe7
github.com/openshift/builder/pkg/build/builder.buildDaemonlessImage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/builder/pkg/build/builder/daemonless.go:172 +0x8af
github.com/openshift/builder/pkg/build/builder.(*DockerBuilder).dockerBuild(0xc4211e7960, 0x19d0440, 0xc420591020, 0xc420805ee0, 0x11, 0xc4205cb950, 0x4e, 0x12ecb87d, 0x268a740)
	/go/src/github.com/openshift/builder/pkg/build/builder/docker.go:381 +0x6c6
github.com/openshift/builder/pkg/build/builder.(*DockerBuilder).Build(0xc4211e7960, 0x0, 0x0)
	/go/src/github.com/openshift/builder/pkg/build/builder/docker.go:138 +0xa6b
github.com/openshift/builder/pkg/build/builder/cmd.dockerBuilder.Build(0x19e0c40, 0xc42014af20, 0x17fdcf8, 0x3, 0x19e4340, 0xc4205ed5e0, 0xc42090ce00, 0xc4206c9040, 0x1, 0x1)
	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:293 +0x16f
github.com/openshift/builder/pkg/build/builder/cmd.(*builderConfig).execute(0xc4206f2460, 0x19b1ce0, 0x26a9698, 0xc4206f2460, 0x0)
	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:278 +0x209
github.com/openshift/builder/pkg/build/builder/cmd.runBuild(0x19b1640, 0xc4200ba010, 0x19b1ce0, 0x26a9698, 0x0, 0x0)
	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:311 +0x80
github.com/openshift/builder/pkg/build/builder/cmd.RunDockerBuild(0x19b1640, 0xc4200ba010, 0xc4200ba010, 0x0)
	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:328 +0x76
main.NewCommandDockerBuilder.func1(0xc4201b7680, 0xc42073c1b0, 0x0, 0x1)
	/go/src/github.com/openshift/builder/cmd/builder.go:88 +0x43
github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201b7680, 0xc4200c0010, 0x1, 0x1, 0xc4201b7680, 0xc4200c0010)
	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201b7680, 0x0, 0xc4200ba2b8, 0xc4200ba2b0)
	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201b7680, 0x16, 0xc4201b7680)
	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/openshift/builder/cmd/main.go:56 +0x37d
<----end of log for "multi-stage-build"/"docker-build"
```

**Comment by mtrmac** [comment]
This looks exactly the same as #1079 – are you running a post-#1082 version?

**Comment by mtrmac** [comment]
> This looks exactly the same as #1079 – are you running a post-#1082 version?

> @mtrmac you can compare what we are running here: https://github.com/openshift/builder/tree/master/vendor/github.com/containers

Yeah, that’s is behind. It seems the repo is vendoring the https://github.com/nalind/image/commits/ip-registry fork of containers/image; update to the current version of it.

**Comment by mtrmac** [comment]
I was unclear: it’s not necessary to leave the branch — the current version of that branch is already up-to-date; the version vendored into openshift/builder is an older version of that branch.

Stay on that branch if you need to, only update to its latest rebase.
