### ISSUE TITLE
nil pointer error building from dockerfile

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1122]
```
    2018-10-21T23:22:21.098964896Z Copying blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
    2018-10-21T23:22:28.491237896Z 
 0 B / 71.23 MiB 
 2.64 MiB / 71.23 MiB 
 4.93 MiB / 71.23 MiB 
 7.46 MiB / 71.23 MiB 
 9.43 MiB / 71.23 MiB 
 11.77 MiB / 71.23 MiB 
 13.50 MiB / 71.23 MiB 
 15.69 MiB / 71.23 MiB 
 17.73 MiB / 71.23 MiB 
 19.73 MiB / 71.23 MiB 
 21.98 MiB / 71.23 MiB 
 24.04 MiB / 71.23 MiB 
 26.18 MiB / 71.23 MiB 
 28.18 MiB / 71.23 MiB 
 30.08 MiB / 71.23 MiB 
 31.69 MiB / 71.23 MiB 
 34.33 MiB / 71.23 MiB 
 36.71 MiB / 71.23 MiB 
 38.68 MiB / 71.23 MiB 
 40.59 MiB / 71.23 MiB 
 41.62 MiB / 71.23 MiB 
 42.90 MiB / 71.23 MiB 
 44.94 MiB / 71.23 MiB 
 46.24 MiB / 71.23 MiB 
 47.45 MiB / 71.23 MiB 
 48.69 MiB / 71.23 MiB 
 50.62 MiB / 71.23 MiB 
 52.78 MiB / 71.23 MiB 
 55.17 MiB / 71.23 MiB 
 57.24 MiB / 71.23 MiB 
 58.94 MiB / 71.23 MiB 
 61.71 MiB / 71.23 MiB 
 63.49 MiB / 71.23 MiB 
 65.23 MiB / 71.23 MiB 
 67.44 MiB / 71.23 MiB 
 69.16 MiB / 71.23 MiB 
 71.21 MiB / 71.23 MiB 
 71.23 MiB / 71.23 MiB  7s
    2018-10-21T23:22:28.491663432Z Copying blob sha256:03f625cd1c87c58145f4dccb474c2bde16e630ed0a73b04c78b17a32df8ed6c4
    2018-10-21T23:22:29.435001599Z 
 0 B / 8.92 MiB 
 2.34 MiB / 8.92 MiB 
 4.28 MiB / 8.92 MiB 
 6.59 MiB / 8.92 MiB 
 8.32 MiB / 8.92 MiB 
 8.92 MiB / 8.92 MiB  0s
    2018-10-21T23:22:29.435222435Z Copying blob sha256:e6ecde3f02819eb52cd96cfa211ee4e6c654cfeda797cf1556fe4dd18d477f28
    2018-10-21T23:22:29.555846027Z 
 0 B / 4.63 KiB 
 4.63 KiB / 4.63 KiB  0s
    2018-10-21T23:22:29.556533835Z Copying blob sha256:79e6026c00814beeeb15d4da99c69f211289421da4674c910d3dd2ce3e3e6c2b
    2018-10-21T23:22:29.726147671Z 
 0 B / 157.87 KiB 
 157.87 KiB / 157.87 KiB  0s
    2018-10-21T23:22:29.726334623Z Copying blob sha256:ba1c23d1d04040ca2953599550576c3fac98539afe81978d96665a8fd6305d85
    2018-10-21T23:22:37.62596723Z 
 0 B / 80.24 MiB 
 1.23 MiB / 80.24 MiB 
 3.29 MiB / 80.24 MiB 
 5.71 MiB / 80.24 MiB 
 7.93 MiB / 80.24 MiB 
 10.06 MiB / 80.24 MiB 
 11.98 MiB / 80.24 MiB 
 13.88 MiB / 80.24 MiB 
 16.04 MiB / 80.24 MiB 
 18.04 MiB / 80.24 MiB 
 19.52 MiB / 80.24 MiB 
 21.91 MiB / 80.24 MiB 
 23.81 MiB / 80.24 MiB 
 25.15 MiB / 80.24 MiB 
 27.01 MiB / 80.24 MiB 
 29.20 MiB / 80.24 MiB 
 32.75 MiB / 80.24 MiB 
 35.38 MiB / 80.24 MiB 
 37.73 MiB / 80.24 MiB 
 39.53 MiB / 80.24 MiB 
 41.82 MiB / 80.24 MiB 
 43.99 MiB / 80.24 MiB 
 46.13 MiB / 80.24 MiB 
 48.03 MiB / 80.24 MiB 
 50.33 MiB / 80.24 MiB 
 52.66 MiB / 80.24 MiB 
 54.90 MiB / 80.24 MiB 
 57.01 MiB / 80.24 MiB 
 59.33 MiB / 80.24 MiB 
 61.74 MiB / 80.24 MiB 
 64.08 MiB / 80.24 MiB 
 66.39 MiB / 80.24 MiB 
 68.28 MiB / 80.24 MiB 
 70.19 MiB / 80.24 MiB 
 72.45 MiB / 80.24 MiB 
 74.64 MiB / 80.24 MiB 
 76.52 MiB / 80.24 MiB 
 77.96 MiB / 80.24 MiB 
 79.57 MiB / 80.24 MiB 
 80.24 MiB / 80.24 MiB  7s
    2018-10-21T23:22:37.626215158Z Copying blob sha256:c1bb31b6e0f46b0cedfd66abf4912dff22441a9e77e8acd21f2576c8edb36d8f
    2018-10-21T23:22:41.453582729Z 
 0 B / 51.51 MiB 
 2.49 MiB / 51.51 MiB 
 4.98 MiB / 51.51 MiB 
 7.15 MiB / 51.51 MiB 
 9.48 MiB / 51.51 MiB 
 11.64 MiB / 51.51 MiB 
 12.62 MiB / 51.51 MiB 
 14.01 MiB / 51.51 MiB 
 16.07 MiB / 51.51 MiB 
 18.36 MiB / 51.51 MiB 
 20.50 MiB / 51.51 MiB 
 23.77 MiB / 51.51 MiB 
 31.11 MiB / 51.51 MiB 
 37.75 MiB / 51.51 MiB 
 42.33 MiB / 51.51 MiB 
 44.72 MiB / 51.51 MiB 
 46.80 MiB / 51.51 MiB 
 48.82 MiB / 51.51 MiB 
 50.87 MiB / 51.51 MiB 
 51.51 MiB / 51.51 MiB  3s
    2018-10-21T23:22:41.453907653Z Copying blob sha256:758221f01a5c51d2d1901eb69e5cef34355c2c44f925c90bd2a1ff096d1ac11e
    2018-10-21T23:22:41.602739279Z 
 0 B / 2.28 KiB 
 2.28 KiB / 2.28 KiB  0s
    2018-10-21T23:22:41.603359916Z Copying blob sha256:61f55663ea3b29d211b8b84449734e99a04b8b41036603f505d5930762edc88d
    2018-10-21T23:22:41.755255748Z 
 0 B / 26.47 KiB 
 26.47 KiB / 26.47 KiB  0s
    2018-10-21T23:22:41.755677796Z Copying blob sha256:6e3abf06c2410ff87a6956d5058041a342c88f9972f3418f5388dbc388bb55c5
    2018-10-21T23:22:41.977577141Z 
 0 B / 253.25 KiB 
 253.25 KiB / 253.25 KiB  0s
    2018-10-21T23:22:41.977604351Z Copying config sha256:e7e1ec515bb9cf13deb8ae26489731dfb6e99a41ac56a61fd67057622429fe25
    2018-10-21T23:22:41.979070328Z 
 0 B / 19.72 KiB 
 19.72 KiB / 19.72 KiB  0s
    2018-10-21T23:22:41.979089355Z Writing manifest to image destination
    2018-10-21T23:22:41.979095878Z Storing signatures    2018-10-21T23:23:22.379532953Z Generating dockerfile with builder image centos/php-70-centos7
    2018-10-21T23:23:22.382038126Z Using buildah to create image temp.builder.openshift.io/e2e-test-cli-test-hooks-bh6xp/mys2itest-4:f34eb954
    2018-10-21T23:23:22.38294221Z STEP 1: FROM centos/php-70-centos7
    2018-10-21T23:23:33.243247131Z panic: runtime error: invalid memory address or nil pointer dereference
    2018-10-21T23:23:33.243266355Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12eed85]
    2018-10-21T23:23:33.243272636Z 
    2018-10-21T23:23:33.243277667Z goroutine 1 [running]:
    2018-10-21T23:23:33.243570223Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties.func2(0x17fff09, 0x5, 0x1826e00)
    2018-10-21T23:23:33.24358567Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:545 +0x205
    2018-10-21T23:23:33.243592542Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).detectProperties(0xc420926240, 0x19d1620, 0xc4201d3b30, 0x24, 0xc42055a480)
    2018-10-21T23:23:33.243598292Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:556 +0x1ab
    2018-10-21T23:23:33.244302583Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerClient).makeRequest(0xc420926240, 0x19d1620, 0xc4201d3b30, 0x17fea6c, 0x3, 0xc42086cb70, 0x2a, 0xc420fa4228, 0x0, 0x0, ...)
    2018-10-21T23:23:33.24431528Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_client.go:373 +0x5a
    2018-10-21T23:23:33.244535167Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).fetchManifest(0xc4206f1180, 0x19d1620, 0xc4201d3b30, 0x1800c33, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    2018-10-21T23:23:33.24455114Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:92 +0x2b7
    2018-10-21T23:23:33.246762085Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).ensureManifestIsLoaded(0xc4206f1180, 0x19d1620, 0xc4201d3b30, 0x0, 0xc420382400)
    2018-10-21T23:23:33.247227702Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:124 +0xa0
    2018-10-21T23:23:33.248999548Z github.com/openshift/builder/vendor/github.com/containers/image/docker.(*dockerImageSource).GetManifest(0xc4206f1180, 0x19d1620, 0xc4201d3b30, 0x0, 0xc420fa4520, 0xc420fa4568, 0x412ea9, 0xc420480e40, 0x30, 0xc420fa4588, ...)
    2018-10-21T23:23:33.249016203Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/docker/docker_image_src.go:81 +0x57
    2018-10-21T23:23:33.249022692Z github.com/openshift/builder/vendor/github.com/containers/image/image.(*UnparsedImage).Manifest(0xc42073bb60, 0x19d1620, 0xc4201d3b30, 0x177d020, 0xc420fa45b8, 0x4136f8, 0x60, 0x1701940, 0x177d001, 0xc42073bb60)
    2018-10-21T23:23:33.249028727Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/image/unparsed.go:46 +0xd7
    2018-10-21T23:23:33.249754094Z github.com/openshift/builder/vendor/github.com/containers/image/copy.isMultiImage(0x19d1620, 0xc4201d3b30, 0x19c2ae0, 0xc42073bb60, 0xc420fa47c8, 0xc4206f1180, 0x0)
    2018-10-21T23:23:33.249790397Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/manifest.go:116 +0x49
    2018-10-21T23:23:33.251064279Z github.com/openshift/builder/vendor/github.com/containers/image/copy.Image(0x19d1620, 0xc4201d3b30, 0xc42047c600, 0x19e1ee0, 0xc42073b9e0, 0x19e2240, 0xc420933b90, 0xc42073baa0, 0x0, 0x0)
    2018-10-21T23:23:33.251081909Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/image/copy/copy.go:152 +0x340
    2018-10-21T23:23:33.251088709Z github.com/openshift/builder/vendor/github.com/containers/buildah.pullImage(0x19d1620, 0xc4201d3b30, 0x19facc0, 0xc4201e8000, 0xc420535aa0, 0x30, 0x0, 0x0, 0x19b2820, 0xc42000e018, ...)
    2018-10-21T23:23:33.251094677Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/pull.go:203 +0x6c2
    2018-10-21T23:23:33.251100365Z github.com/openshift/builder/vendor/github.com/containers/buildah.pullAndFindImage(0x19d1620, 0xc4201d3b30, 0x19facc0, 0xc4201e8000, 0xc420535aa0, 0x30, 0xc42081dd40, 0xc4208dc285, 0x15, 0x0, ...)
    2018-10-21T23:23:33.251106311Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:43 +0x14d
    2018-10-21T23:23:33.251111652Z github.com/openshift/builder/vendor/github.com/containers/buildah.resolveImage(0x19d1620, 0xc4201d3b30, 0xc4200e1a40, 0x19facc0, 0xc4201e8000, 0xc42081dd40, 0xc4208dc285, 0x15, 0x0, 0x0, ...)
    2018-10-21T23:23:33.251117556Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:194 +0xde2
    2018-10-21T23:23:33.251342513Z github.com/openshift/builder/vendor/github.com/containers/buildah.newBuilder(0x19d1620, 0xc4201d3b30, 0x19facc0, 0xc4201e8000, 0xc42081dd40, 0xc4208dc285, 0x15, 0x0, 0x0, 0x0, ...)
    2018-10-21T23:23:33.251355176Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/new.go:250 +0x17e1
    2018-10-21T23:23:33.251361675Z github.com/openshift/builder/vendor/github.com/containers/buildah.NewBuilder(0x19d1620, 0xc4201d3b30, 0x19facc0, 0xc4201e8000, 0xc42081dd40, 0xc4208dc285, 0x15, 0x0, 0x0, 0x0, ...)
    2018-10-21T23:23:33.251367337Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/buildah.go:401 +0x97
    2018-10-21T23:23:33.25195332Z github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Prepare(0xc4203b8dc0, 0x19d1620, 0xc4201d3b30, 0x0, 0x188b358, 0x1, 0xc4200d18c0, 0xc42096a540, 0x0, 0x0, ...)
    2018-10-21T23:23:33.251966795Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:674 +0x3c2
    2018-10-21T23:23:33.252812739Z github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.(*Executor).Build(0xc4200d0dc0, 0x19d1620, 0xc4201d3b30, 0xc42081def0, 0x1, 0x1, 0x0, 0x0)
    2018-10-21T23:23:33.25286411Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:1192 +0x1f2
    2018-10-21T23:23:33.25344296Z github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x19d1620, 0xc4201d3b30, 0x19facc0, 0xc4201e8000, 0x180fd9d, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
    2018-10-21T23:23:33.253838259Z 	/go/src/github.com/openshift/builder/vendor/github.com/containers/buildah/imagebuildah/build.go:1335 +0xfe7
    2018-10-21T23:23:33.253853847Z github.com/openshift/builder/pkg/build/builder.buildDaemonlessImage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    2018-10-21T23:23:33.253883574Z 	/go/src/github.com/openshift/builder/pkg/build/builder/daemonless.go:172 +0x8af
    2018-10-21T23:23:33.253947224Z github.com/openshift/builder/pkg/build/builder.(*S2IBuilder).buildImage(0xc42096d620, 0x180fd9d, 0x12, 0x17ff11b, 0x4, 0xc420fa76f8, 0x0, 0x0)
    2018-10-21T23:23:33.255804292Z 	/go/src/github.com/openshift/builder/pkg/build/builder/sti.go:469 +0x310
    2018-10-21T23:23:33.255834737Z github.com/openshift/builder/pkg/build/builder.(*S2IBuilder).Build(0xc42096d620, 0x0, 0x0)
    2018-10-21T23:23:33.255841334Z 	/go/src/github.com/openshift/builder/pkg/build/builder/sti.go:359 +0x1a19
    2018-10-21T23:23:33.255846952Z github.com/openshift/builder/pkg/build/builder/cmd.s2iBuilder.Build(0x19e1e20, 0xc420334c60, 0x17fed18, 0x3, 0x19e5520, 0xc420451320, 0xc420952e00, 0xc4206f0900, 0x1, 0x1)
    2018-10-21T23:23:33.257025198Z 	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:300 +0x15d
    2018-10-21T23:23:33.258229094Z github.com/openshift/builder/pkg/build/builder/cmd.(*builderConfig).execute(0xc4204e37a0, 0x19b2ee0, 0x26aa758, 0xc4204e37a0, 0x0)
    2018-10-21T23:23:33.258246344Z 	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:278 +0x209
    2018-10-21T23:23:33.258253331Z github.com/openshift/builder/pkg/build/builder/cmd.runBuild(0x19b2820, 0xc42000e020, 0x19b2ee0, 0x26aa758, 0x0, 0x0)
    2018-10-21T23:23:33.258259068Z 	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:311 +0x80
    2018-10-21T23:23:33.258264575Z github.com/openshift/builder/pkg/build/builder/cmd.RunS2IBuild(0x19b2820, 0xc42000e020, 0xc42000e020, 0x0)
    2018-10-21T23:23:33.258269712Z 	/go/src/github.com/openshift/builder/pkg/build/builder/cmd/builder.go:338 +0x94
    2018-10-21T23:23:33.258275451Z main.NewCommandS2IBuilder.func1(0xc420152780, 0xc4206cbdf0, 0x0, 0x1)
    2018-10-21T23:23:33.258280553Z 	/go/src/github.com/openshift/builder/cmd/builder.go:72 +0x43
    2018-10-21T23:23:33.258337934Z github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).execute(0xc420152780, 0xc42000c090, 0x1, 0x1, 0xc420152780, 0xc42000c090)
    2018-10-21T23:23:33.258358012Z 	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
    2018-10-21T23:23:33.261060991Z github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420152780, 0x2b, 0xc4207bdb30, 0xc4200fa480)
    2018-10-21T23:23:33.26107227Z 	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:852 +0x30a
    2018-10-21T23:23:33.261078184Z github.com/openshift/builder/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420152780, 0x13, 0xc420152780)
    2018-10-21T23:23:33.261083523Z 	/go/src/github.com/openshift/builder/vendor/github.com/spf13/cobra/command.go:800 +0x2b
    2018-10-21T23:23:33.26108895Z main.main()
    2018-10-21T23:23:33.261094141Z 	/go/src/github.com/openshift/builder/cmd/main.go:74 +0x90d
```

**Comment by bparees** [comment]
in retrospect this is probably a dupe of https://github.com/containers/buildah/issues/1105

closing it, will reopen if it recreates after bumping our deps.
