### ISSUE TITLE
hang during copy

### ISSUE THREAD

**Issue by ohadlevy** [containers/buildah#1578]
When trying to build, using a multi-stage build, podman/buildah just hangs during the command
```
STEP 53: COPY --chown=1001:1001 . ${HOME}/
```

**Steps to reproduce the issue:**
1. checkout https://github.com/ohadlevy/foreman/tree/containers
2. podman build .
3.

**Describe the results you received:**
podman hangs

**Describe the results you expected:**
that it would work ;)

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.7-2.git873f001.fc29.x86_64
```

**Output of `buildah version`:**

```
Version:         1.7
Go Version:      go1.11.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 02:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64

```

**Output of `cat /etc/*release`:**

```
Fedora release 29 (Twenty Nine)
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 29 (Twenty Nine)
Fedora release 29 (Twenty Nine)
```

**Output of `uname -a`:**

```
Linux ohad 5.0.9-200.fc29.x86_64 #1 SMP Mon Apr 22 00:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base.
# device.
# mkfsarg = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver 
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

# If specified, use OSTree to deduplicate files with the overlay backend
ostree_repo = ""

# Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
# certain container storage drivers
skip_mount_home = "false"

```

**Comment by TomSweeneyRedHat** [comment]
@ohadlevy thanks for the issue report, I'm giving it a quick test now.

**Comment by TomSweeneyRedHat** [comment]
OK, I did `git clone https://github.com/ohadlevy/foreman/tree/containers` and it didn't pull entrypoint.sh or Dockerfile.  Looks like it got most everything else.  weird.

**Comment by TomSweeneyRedHat** [comment]
I've a suspicion this and #1546 are related.

**Comment by ohadlevy** [comment]
Make sure you pulled the containers branch? Thanks!

**Comment by TomSweeneyRedHat** [comment]
I think I did, I cut/pasted my clone command in the prior reply.  I ran into what appear to be non-related errors with python and/or the foreman build.  if you've thoughts on how to get around that, I'd be happy to hear them.  I've got to log for a bit,will be back online later.

Also if you've the time, if you could clone, make and install podman from upstream and try that, it would be a good datapoint to have.

```
STEP 30: RUN entrypoint.sh npm install --no-optional && entrypoint.sh npm rebuild node-sass --force

> TheForemanDevDeps@1.19.0 postinstall /home/foreman
> node ./script/npm_install_plugins.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 30842 packages in 38.006s
found 114 vulnerabilities (29 low, 44 moderate, 41 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN using --force I sure hope you know what you are doing.

> node-sass@4.12.0 install /home/foreman/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-67_binding.node
Download complete  ] - :
Binary saved to /home/foreman/node_modules/node-sass/vendor/linux-x64-67/binding.node
Caching binary to /home/foreman/.npm/node-sass/4.12.0/linux-x64-67_binding.node

> node-sass@4.12.0 postinstall /home/foreman/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/foreman/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/foreman/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.14.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/foreman/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/foreman/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/foreman/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/foreman/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/foreman/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/foreman/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/foreman/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/foreman/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/foreman/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/foreman/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)\n    at F (/home/foreman/node_modules/which/which.js:68:19)\n    at E (/home/foreman/node_modules/which/which.js:80:29)\n    at /home/foreman/node_modules/which/which.js:89:16\n    at /home/foreman/node_modules/isexe/index.js:42:5\n    at /home/foreman/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/foreman/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/foreman/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/foreman/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/foreman/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/foreman/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/foreman/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/foreman/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/foreman/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/foreman/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/foreman/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/home/foreman/node_modules/which/which.js:13:12)\n    at F (/home/foreman/node_modules/which/which.js:68:19)\n    at E (/home/foreman/node_modules/which/which.js:80:29)\n    at /home/foreman/node_modules/which/which.js:89:16\n    at /home/foreman/node_modules/isexe/index.js:42:5\n    at /home/foreman/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/foreman/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/foreman/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/foreman/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/foreman/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/foreman/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/foreman/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/foreman/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 5.0.8-300.fc30.x86_64
gyp ERR! command "/usr/bin/node" "/home/foreman/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/foreman/node_modules/node-sass
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

```

**Comment by ohadlevy** [comment]
thanks, you've got further than what I got with podman, are there nightly rpm builds or should i install from source? thanks.

**Comment by TomSweeneyRedHat** [comment]
The closest we have is:  https://copr.fedorainfracloud.org/coprs/baude/Upstream_CRIO_Family/.  I've not tried it myself, got the pointer from @baude.  Other than that it's clone time.

**Comment by ohadlevy** [comment]
I've updated to git based version and rerun - similar issue.. I have no idea how to reproduce the issue you had above. 

```
STEP 26: COPY package.json ${HOME}
--> c51d459f0e57a3cddde4bd784cf936f6f965102de506040c8b371c831b43e7b5
STEP 27: RUN entrypoint.sh npm install --ignore-scripts --no-optional
npm WARN deprecated jquery-flot@0.8.3: flot has been abandoned
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN redux-form@8.2.0 requires a peer of react-redux@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux-test-utils@0.1.1 requires a peer of react-redux@6.x but none is installed. You must install peer dependencies yourself.
npm WARN react-redux-test-utils@0.1.1 requires a peer of redux@4.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2181 packages from 1902 contributors and audited 46358 packages in 142.727s
found 148 vulnerabilities (64 low, 44 moderate, 40 high)
  run `npm audit fix` to fix them, or `npm audit` for details
--> 611f1d41c17025bdac431f622d017a59c2a782befbc8d9cceab9807fa245ec3c
STEP 28: COPY --chown=1001:1001 . ${HOME}/
```

whats the right way to debug the copy process? thanks!

**Comment by TomSweeneyRedHat** [comment]
@ohadlevy The only real debugging we have is the `--debug` option which can be used immediately after the word `buildah` in any buildah command.  i.e. `buildah --debug bud ...`   Other than that, it's a matter of running through the code, adding further debug statements as necessary, and running down the issue.
Just to verify, were you running this as a root or non-root user?  If a non-root user, had you setup subuid and subgid appropriately?

**Comment by nalind** [comment]
I think this is #1583.

**Comment by iNecas** [comment]
I've hit the very same issue. The minimal reproducer is here:

```
git clone git@github.com:theforeman/foreman.git
cd foreman
cat <<EOF > Dockerfile.chownrepro
FROM registry.fedoraproject.org/fedora-minimal:30

ARG HOME=/home/testuser

WORKDIR \$HOME

RUN groupadd -r testuser -f -g 1001 && \
    useradd -u 1001 -r -g testuser -d \$HOME -s /sbin/nologin \
    testuser && \
    chown -R 1001:1001 \$HOME

COPY --chown=1001:1001 . \$HOME/

ENTRYPOINT ["ls", "-al", "/home/testuser"]
EOF

buildah bud -t chown-repro -f Dockerfile.chownrepro .
podman run -ti --rm chown-repro
# notice how long the COPY command takes and that all the directories
# having `root` owner instead of `testuser`
```

Seems it has something to do with the amount of files or depth of the file structure. I don't see this issue with simpler dir structure.

**Output of `buildah version`:**

```
buildah version          
Version:         1.8.2
Go Version:      go1.11.7
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.11.7
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
@iNecas could you check this against master branch?

**Comment by ohadlevy** [comment]
I just tried latest master (fcb7c14c5bb94583db2343faaa1b85f0f2f96092) with
the same results.

**Comment by lzap** [comment]
I just tried this with

```
[root@box lzap]# podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
[root@box lzap]# buildah version
Version:         1.10.1
Go Version:      go1.12.7
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

And it works fine. The COPY line does not get stuck.

**Comment by iNecas** [comment]
ACK, I've seen the improvements as well. Might be ok to close
