### ISSUE TITLE
buildah push: got segfault, specifying empty image name and any destination

### ISSUE THREAD

**Issue by singul0** [containers/buildah#1708]
Subj. Not a big deal, cause it sure is incorrect usage, but I strongly suppose segfaults should not be allowed in any program.

**Steps to reproduce the issue:**
1. Run `buildah push "" example.com" or any other destination, it doesn't matter.

**Describe the results you received:**
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x917c0c]

goroutine 1 [running]:
github.com/containers/buildah/vendor/github.com/containers/image/copy.Image(0xf29260, 0xc0000380b8, 0xc000216140, 0xf353c0, 0xc0001675a0, 0x0, 0x0, 0xc000364ba0, 0x0, 0x0, ...)
        /go/src/github.com/containers/buildah/vendor/github.com/containers/image/copy/copy.go:151 +0x17c
github.com/containers/buildah.Push(0xf29260, 0xc0000380b8, 0x7ffe7c308ee4, 0x0, 0xf353c0, 0xc0001675a0, 0x2, 0x0, 0x0, 0xf135a0, ...)
        /go/src/github.com/containers/buildah/commit.go:324 +0x2a6
main.pushCmd(0xc000303b80, 0xc00000f580, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/containers/buildah/cmd/buildah/push.go:163 +0x354
main.init.15.func1(0xc000303b80, 0xc00000f580, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/containers/buildah/cmd/buildah/push.go:54 +0xc5
github.com/containers/buildah/vendor/github.com/spf13/cobra.(*Command).execute(0xc000303b80, 0xc00000f540, 0x2, 0x2, 0xc000303b80, 0xc00000f540)
        /go/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/containers/buildah/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1541dc0, 0xc0000aabd0, 0x7ffe7c308ed7, 0x7)
        /go/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/containers/buildah/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/github.com/containers/buildah/cmd/buildah/main.go:125 +0x91
```

**Describe the results you expected:**

Nice error message

**Output of `buildah version`:**

```
Version:         1.9.0
Go Version:      go1.12.6
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
3.10.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.0
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Output of `uname -a`:**

```
Linux d269775a4033 4.19.52-gentoo #9 SMP Thu Jul 4 18:05:11 EEST 2019 x86_64 Linux
```

**Output of `cat /etc/containers/storage.conf`:**

I dont't have one

**Comment by rhatdan** [comment]
@QiWang19 PTAL
