### ISSUE TITLE
buildah bud panics with SIGSEGV when passed a file instead of a folder

### ISSUE THREAD

**Issue by danieldulaney** [containers/buildah#1824]
**Description**

When `buildah bud` is called with a file instead of a folder as the only argument, it panics with SIGSEGV.

**Steps to reproduce the issue:**

```
touch foobar
buildah bud foobar
```

**Describe the results you received:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55feaebb6a73]
goroutine 1 [running]:
github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x55feaf130a20, 0xc000038158, 0x55feaf146800, 0xc0003437a0, 0xc000386240, 0x2f, 0x0, 0x0, 0x0, 0x0, ...)        /build/buildah/src/src/github.com/containers/buildah/imagebuildah/build.go:201 +0xd83
main.budCmd(0xc0002dd900, 0xc000178410, 0x1, 0x1, 0xc0007a6ff8, 0xc00051e600, 0xc000536ba0, 0xc00051e780, 0xc000536c00, 0x0, ...)
        /build/buildah/src/src/github.com/containers/buildah/cmd/buildah/bud.go:292 +0x121bmain.init.1.func1(0xc0002dd900, 0xc000178410, 0x1, 0x1, 0x0, 0x0)
        /build/buildah/src/src/github.com/containers/buildah/cmd/buildah/bud.go:50 +0xd8github.com/spf13/cobra.(*Command).execute(0xc0002dd900, 0xc0001782c0, 0x1, 0x1, 0xc0002dd900, 0xc0001782c0)
        /build/buildah/src/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0x55feaf762e80, 0xc000032c30, 0x7ffe51a7a514, 0x1b)
        /build/buildah/src/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/spf13/cobra.(*Command).Execute(...)
        /build/buildah/src/src/github.com/containers/buildah/vendor/github.com/spf13/cobra/command.go:800
main.main()        /build/buildah/src/src/github.com/containers/buildah/cmd/buildah/main.go:125 +0x93
ERRO[0000] exit status 2
```

**Describe the results you expected:**

An error message telling me that I should use `-f` to pass the path to a Dockerfile, and that the argument is the path to the context directory.

**Output of `rpm -q buildah` or `apt list buildah` [or `pacman -Qi buildah`]:**

```
$ pacman -Qi buildah
Name            : buildah
Version         : 1.10.1-1
Description     : A tool which facilitates building OCI images
Architecture    : x86_64
URL             : https://github.com/containers/buildah
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : ostree  runc  skopeo
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 24.99 MiB
Packager        : Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Sat 17 Aug 2019 03:40:34 PM EDT
Install Date    : Wed 21 Aug 2019 01:03:46 AM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.10.1
Go Version:      go1.12.8
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.1
Git Commit:      8c1c2c58
Built:           Sat Aug 17 15:41:23 2019
OS/Arch:         linux/amd64 
```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

```
$ cat /etc/*release
Arch Linux release
LSB_VERSION=1.4
DISTRIB_ID=ArchDISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"ID=arch
BUILD_ID=rollingANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Output of `uname -a`:**

```
$ uname -a
Linux boron 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ cat /etc/containers/storage.conf
# This file is is the configuration file for all tools# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base.
# device.
# mkfsarg = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver 
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

# If specified, use OSTree to deduplicate files with the overlay backend
ostree_repo = ""

# Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
# certain container storage drivers
skip_mount_home = "false"
```

**Comment by TomSweeneyRedHat** [comment]
Well that's certainly not pretty.  Thanks for the issue @danieldulaney

**Comment by rhatdan** [comment]
```
$ buildah bud foobar
error reading info about "/home/dwalsh/buildah/foobar/Dockerfile": stat /home/dwalsh/buildah/foobar/Dockerfile: not a directory
ERRO[0000] exit status 1                                
```
Seems to be fixed in master.
```
$ buildah version
Version:         1.9.0-dev
Go Version:      go1.12.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-rc2
Git Commit:      aa543b35
Built:           Thu May 23 10:00:02 2019
OS/Arch:         linux/amd64
```
