### ISSUE TITLE
Panic when attempting to build from digest

### ISSUE THREAD

**Issue by ari-becker** [containers/buildah#2049]
**Description**

When attempting to build from a digest, buildah panics.

**Steps to reproduce the issue:**

with Dockerfile (the first line is supposed to be equivalent to `alpine:3.8`):
```dockerfile
FROM alpine@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528

RUN apk add bash

CMD ["/bin/bash"]
```

run `buildah bud .`

**Describe the results you received:**
```text
STEP 1: FROM alpine@sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528

Getting image source signatures

Copying blob 4fe2ade4980c done

Copying config 196d12cf6a done

Writing manifest to image destination

Storing signatures

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x56532c60cd78]


goroutine 1 [running]:

panic(0x56532cc36b20, 0x56532d611740)

	/usr/lib/golang/src/runtime/panic.go:722 +0x2c6 fp=0xc0006e14e8 sp=0xc0006e1458 pc=0x56532baa31d6

runtime.panicmem(...)

	/usr/lib/golang/src/runtime/panic.go:199

runtime.sigpanic()

	/usr/lib/golang/src/runtime/signal_unix.go:394 +0x3f0 fp=0xc0006e1518 sp=0xc0006e14e8 pc=0x56532bab84e0

github.com/containers/buildah.unmarshalConvertedConfig(0x56532cdf43a0, 0xc0000b6070, 0x56532cb86960, 0xc000258b40, 0x7fb83166c320, 0xc0005ce760, 0x56532c7378b7, 0x34, 0x0, 0x0)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/config.go:38 +0x588 fp=0xc0006e1708 sp=0xc0006e1518 pc=0x56532c60cd78

github.com/containers/buildah.(*Builder).initConfig(0xc0002e6000, 0x56532cdf43a0, 0xc0000b6070, 0x7fb83166c320, 0xc0005ce760, 0x0, 0x0)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/config.go:65 +0x1fb fp=0xc0006e17d8 sp=0xc0006e1708 pc=0x56532c60d1eb

github.com/containers/buildah.newBuilder(0x56532cdf43a0, 0xc0000b6070, 0x56532ce15580, 0xc0001779e0, 0xc000256b70, 0xc00003e410, 0x4e, 0x0, 0x0, 0x0, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/new.go:373 +0xe75 fp=0xc0006e1c68 sp=0xc0006e17d8 pc=0x56532c620285

github.com/containers/buildah.NewBuilder(...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/buildah.go:448

github.com/containers/buildah/imagebuildah.(*StageExecutor).prepare(0xc0000d3080, 0x56532cdf43a0, 0xc0000b6070, 0x0, 0x56532c7199c1, 0x1, 0xc0000e1b80, 0xc00047f650, 0xc00003e410, 0x4e, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/imagebuildah/stage_executor.go:613 +0x404 fp=0xc0006e2710 sp=0xc0006e1c68 pc=0x56532c68e5c4

github.com/containers/buildah/imagebuildah.(*StageExecutor).Execute(0xc0000d3080, 0x56532cdf43a0, 0xc0000b6070, 0x0, 0x56532c7199c1, 0x1, 0xc0000e1b80, 0xc00047f650, 0xc00003e410, 0x4e, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/imagebuildah/stage_executor.go:741 +0x16a fp=0xc0006e2b00 sp=0xc0006e2710 pc=0x56532c68fcda

github.com/containers/buildah/imagebuildah.(*Executor).Build(0xc000264f00, 0x56532cdf43a0, 0xc0000b6070, 0xc000257c50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/imagebuildah/executor.go:467 +0x898 fp=0xc0006e2fa0 sp=0xc0006e2b00 pc=0x56532c686c38

github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x56532cdf43a0, 0xc0000b6070, 0x56532ce15580, 0xc0001779e0, 0xc000104600, 0x1e, 0x0, 0x0, 0x0, 0x0, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/imagebuildah/build.go:263 +0x5df fp=0xc0006e3408 sp=0xc0006e2fa0 pc=0x56532c6813af

main.budCmd(0xc000388a00, 0xc000256ab0, 0x1, 0x3, 0xc000190ad8, 0xc000095380, 0xc0004cfc20, 0xc000016e00, 0xc0004cfc80, 0x0, ...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/cmd/buildah/bud.go:324 +0x11e5 fp=0xc0006e3ca8 sp=0xc0006e3408 pc=0x56532c6b8bf5

main.init.1.func1(0xc000388a00, 0xc000256ab0, 0x1, 0x3, 0x0, 0x0)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/cmd/buildah/bud.go:55 +0xd8 fp=0xc0006e3d38 sp=0xc0006e3ca8 pc=0x56532c6e6b38

github.com/spf13/cobra.(*Command).execute(0xc000388a00, 0xc000256a50, 0x3, 0x3, 0xc000388a00, 0xc000256a50)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/src/github.com/spf13/cobra/command.go:826 +0x462 fp=0xc0006e3e10 sp=0xc0006e3d38 pc=0x56532c6754e2

github.com/spf13/cobra.(*Command).ExecuteC(0x56532d621420, 0x6, 0x56532c6f301e, 0x8)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/src/github.com/spf13/cobra/command.go:914 +0x2fd fp=0xc0006e3ee8 sp=0xc0006e3e10 pc=0x56532c675f3d

github.com/spf13/cobra.(*Command).Execute(...)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/src/github.com/spf13/cobra/command.go:864

main.main()

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/_build/src/github.com/containers/buildah/cmd/buildah/main.go:141 +0xb6 fp=0xc0006e3f60 sp=0xc0006e3ee8 pc=0x56532c6d3f76

runtime.main()

	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc0006e3fe0 sp=0xc0006e3f60 pc=0x56532baa4f46

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0006e3fe8 sp=0xc0006e3fe0 pc=0x56532bad0f21


goroutine 2 [force gc (idle)]:

runtime.gopark(0x56532cdaf180, 0x56532d684010, 0x1411, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000054fb0 sp=0xc000054f90 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.forcegchelper()

	/usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc000054fe0 sp=0xc000054fb0 pc=0x56532baa51db

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x56532bad0f21

created by runtime.init.6

	/usr/lib/golang/src/runtime/proc.go:242 +0x37


goroutine 3 [GC sweep wait]:

runtime.gopark(0x56532cdaf180, 0x56532d686380, 0x140c, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0000557a8 sp=0xc000055788 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.bgsweep(0xc00007a000)

	/usr/lib/golang/src/runtime/mgcsweep.go:89 +0x135 fp=0xc0000557d8 sp=0xc0000557a8 pc=0x56532ba976b5

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000557e0 sp=0xc0000557d8 pc=0x56532bad0f21

created by runtime.gcenable

	/usr/lib/golang/src/runtime/mgc.go:210 +0x5e


goroutine 4 [GC scavenge wait]:

runtime.gopark(0x56532cdaf180, 0x56532d686920, 0x140d, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000055f38 sp=0xc000055f18 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.bgscavenge(0xc00007a000)

	/usr/lib/golang/src/runtime/mgcscavenge.go:332 +0x3ed fp=0xc000055fd8 sp=0xc000055f38 pc=0x56532ba96f6d

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000055fe0 sp=0xc000055fd8 pc=0x56532bad0f21

created by runtime.gcenable

	/usr/lib/golang/src/runtime/mgc.go:211 +0x80


goroutine 18 [finalizer wait]:

runtime.gopark(0x56532cdaf180, 0x56532d6a5f20, 0xc000451410, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000054758 sp=0xc000054738 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.runfinq()

	/usr/lib/golang/src/runtime/mfinal.go:175 +0xa7 fp=0xc0000547e0 sp=0xc000054758 pc=0x56532ba8d547

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000547e8 sp=0xc0000547e0 pc=0x56532bad0f21

created by runtime.createfing

	/usr/lib/golang/src/runtime/mfinal.go:156 +0x63


goroutine 19 [timer goroutine (idle)]:

runtime.gopark(0x56532cdaf180, 0x56532d68d520, 0x1415, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000050760 sp=0xc000050740 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.timerproc(0x56532d68d520)

	/usr/lib/golang/src/runtime/time.go:303 +0x27f fp=0xc0000507d8 sp=0xc000050760 pc=0x56532bac1a3f

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000507e0 sp=0xc0000507d8 pc=0x56532bad0f21

created by runtime.(*timersBucket).addtimerLocked

	/usr/lib/golang/src/runtime/time.go:169 +0x110


goroutine 12 [GC worker (idle)]:

runtime.gopark(0x56532cdaf018, 0xc000422880, 0x56532ba71418, 0x0)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000050f60 sp=0xc000050f40 pc=0x56532baa5336

runtime.gcBgMarkWorker(0xc000042000)

	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc000050fd8 sp=0xc000050f60 pc=0x56532ba90f75

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000050fe0 sp=0xc000050fd8 pc=0x56532bad0f21

created by runtime.gcBgMarkStartWorkers

	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79


goroutine 11 [syscall]:

runtime.notetsleepg(0x56532d6a66c0, 0xffffffffffffffff, 0xc0000517c8)

	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000051798 sp=0xc000051768 pc=0x56532ba7fbc8

os/signal.signal_recv(0x0)

	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e fp=0xc0000517c0 sp=0xc000051798 pc=0x56532bab92fe

os/signal.loop()

	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc0000517e0 sp=0xc0000517c0 pc=0x56532c081114

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000517e8 sp=0xc0000517e0 pc=0x56532bad0f21

created by os/signal.init.0

	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43


goroutine 28 [GC worker (idle)]:

runtime.gopark(0x56532cdaf018, 0xc000354390, 0x56532ba71418, 0x0)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000051f60 sp=0xc000051f40 pc=0x56532baa5336

runtime.gcBgMarkWorker(0xc000044500)

	/usr/lib/golang/src/runtime/mgc.go:1837 +0x105 fp=0xc000051fd8 sp=0xc000051f60 pc=0x56532ba90f75

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000051fe0 sp=0xc000051fd8 pc=0x56532bad0f21

created by runtime.gcBgMarkStartWorkers

	/usr/lib/golang/src/runtime/mgc.go:1785 +0x79


goroutine 31 [chan receive]:

runtime.gopark(0x56532cdaf180, 0xc0000ba1d8, 0x170e, 0x3)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0000566d0 sp=0xc0000566b0 pc=0x56532baa5336

runtime.goparkunlock(...)

	/usr/lib/golang/src/runtime/proc.go:310

runtime.chanrecv(0xc0000ba180, 0xc0000567b0, 0xc0000bc001, 0xc0000ba180)

	/usr/lib/golang/src/runtime/chan.go:524 +0x2ec fp=0xc000056760 sp=0xc0000566d0 pc=0x56532ba7a8cc

runtime.chanrecv2(0xc0000ba180, 0xc0000567b0, 0x56532c12b8eb)

	/usr/lib/golang/src/runtime/chan.go:411 +0x2b fp=0xc000056790 sp=0xc000056760 pc=0x56532ba7a5cb

k8s.io/klog.(*loggingT).flushDaemon(0x56532d6876a0)

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/src/k8s.io/klog/klog.go:990 +0x8d fp=0xc0000567d8 sp=0xc000056790 pc=0x56532c21873d

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000567e0 sp=0xc0000567d8 pc=0x56532bad0f21

created by k8s.io/klog.init.0

	/builddir/build/BUILD/buildah-21b4778b359ef7d6efe877c2f90f3df67ad93609/src/k8s.io/klog/klog.go:404 +0x6e


goroutine 13 [syscall]:

runtime.notetsleepg(0x56532d68d4c0, 0x79db4e40, 0x0)

	/usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000150760 sp=0xc000150730 pc=0x56532ba7fbc8

runtime.timerproc(0x56532d68d4a0)

	/usr/lib/golang/src/runtime/time.go:311 +0x2f5 fp=0xc0001507d8 sp=0xc000150760 pc=0x56532bac1ab5

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001507e0 sp=0xc0001507d8 pc=0x56532bad0f21

created by runtime.(*timersBucket).addtimerLocked

	/usr/lib/golang/src/runtime/time.go:169 +0x110


goroutine 84 [select, locked to thread]:

runtime.gopark(0x56532cdaf1c0, 0x0, 0x1809, 0x1)

	/usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0001535e0 sp=0xc0001535c0 pc=0x56532baa5336

runtime.selectgo(0xc000153780, 0xc000153740, 0x2, 0x8, 0x1)

	/usr/lib/golang/src/runtime/select.go:313 +0xca1 fp=0xc000153708 sp=0xc0001535e0 pc=0x56532bab4671

runtime.ensureSigM.func1()

	/usr/lib/golang/src/runtime/signal_unix.go:549 +0x1ea fp=0xc0001537e0 sp=0xc000153708 pc=0x56532bace58a

runtime.goexit()

	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001537e8 sp=0xc0001537e0 pc=0x56532bad0f21

created by runtime.ensureSigM

	/usr/lib/golang/src/runtime/signal_unix.go:532 +0xd7
```

**Describe the results you expected:**

Not a panic

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.11.4-2.fc31.x86_64
```

**Output of `buildah version`:**

```
Version:         1.11.4
Go Version:      go1.13.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**
N/A

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)                                                                        
NAME=Fedora                                                                                           
VERSION="31 (Container Image)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux d7e2ef19-b201-414b-7a80-a2bd9bffad91 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools                 
# that use the containers/storage library.                             
# See man 5 containers-storage.conf for more information               
# The "container storage" table contains all of the server options.    
[storage]

# Default Storage Driver
driver = "vfs"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"                                                             
                                                                                                       
# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version                 
override_kernel_check = "true"                                                                         
                                                                                                       
# mountopt specifies comma separated list of extra mount options                                       
#mountopt = "nodev,metacopy=on"                                                                        
                                                                                                       
# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of                        
# a container, to UIDs/GIDs as they should appear outside of the container, and                        
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed                          
# and will be heeded by libraries, but there are limits to the number of                               
# mappings which the kernel will allow when you later attempt to run a                                 
# container.                                                                                           
#                                                                                                      
# remap-uids = 0:1668442479:65536                                                                      
# remap-gids = 0:1668442479:65536                                                                      
                                                                                                       
# Remap-User/Group is a name which can be used to look up one or more UID/GID                          
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting                         
# with an in-container ID of 0 and the a host-level ID taken from the lowest     
# range that matches the specified name, and using the length of that range.     
# Additional ranges are then assigned, using the ranges which specify the        
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,  
# until all of the entries have been used for maps.                              
#                                                                                
# remap-user = "storage"                                                         
# remap-group = "storage"                                                        
                                                                                 
[storage.options.thinpool]                                                       
# Storage Options for thinpool                                                   
                                                                                 
# autoextend_percent determines the amount by which pool needs to be             
# grown. This is specified in terms of % of pool size. So a value of 20 means    
# that when threshold is hit, pool will be grown by 20% of existing              
# pool size.                                                                     
# autoextend_percent = "20"                                                      
                                                                                 
# autoextend_threshold determines the pool extension threshold in terms          
# of percentage of pool size. For example, if threshold is 60, that means when   
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"
                                                                                  
# log_level sets the log level of devicemapper.                                   
# 0: LogLevelSuppress 0 (Default)                                                 
# 2: LogLevelFatal                                                                
# 3: LogLevelErr                                                                  
# 4: LogLevelWarn                                                                 
# 5: LogLevelNotice                                                               
# 6: LogLevelInfo                                                                 
# 7: LogLevelDebug                                                                
# log_level = "7"                                                                 
                                                                                  
# min_free_space specifies the min free space percent in a thin pool require for  
# new device creation to succeed. Valid values are from 0% - 99%.                 
# Value 0% disables                                                               
# min_free_space = "10%"                                                          
                                                                                  
# mkfsarg specifies extra mkfs arguments to be used when creating the base.                      
# device.                                                                                        
# mkfsarg = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver 
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

# If specified, use OSTree to deduplicate files with the overlay backend
ostree_repo = ""

# Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
# certain container storage drivers
skip_mount_home = "false"
```

**Comment by TomSweeneyRedHat** [comment]
@ari-becker thanks for the issue.  Most of the team is off until the new year enjoying the holidays.  If someone doesn't hop on before, we'll take a look right after the new year.

@mtrmac any off the cuff thoughts?

**Comment by mtrmac** [comment]
In 1.11.4, https://github.com/containers/buildah/blob/21b4778b359ef7d6efe877c2f90f3df67ad93609/config.go#L29 fails, returning  `(nil, err)`, and https://github.com/containers/buildah/blob/21b4778b359ef7d6efe877c2f90f3df67ad93609/config.go#L38 tries to use this `nil`.

This was fixed in https://github.com/containers/buildah/commit/4e03c80a0bf213fd2d7f9ca0c9934c4fb40ae4d6 .

**Comment by rhatdan** [comment]
This is fixed in master. Please try it out from there.  We should have a new version in Fedora 31 soon.
