### ISSUE TITLE
Runtime panic during buildah run

### ISSUE THREAD

**Issue by charlie-ht** [containers/buildah#3130]
**Description**

During a buildad run command, I get a runtime panic. Full job output is available here,
https://gitlab.freedesktop.org/tanty/mesa-valve-ci/-/jobs/8593805

**Steps to reproduce the issue:**
1. Non-deterministic issue, no steps to reproduce
2.
3.

**Describe the results you received:**
```
      + buildah run --isolation chroot x86_test-vk-working-container-82 env DEBIAN_FRONTEND=noninteractive apt-get install -y curl
runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc000085778, fp:0xc0000857b0} stack=[0xc000085000,0xc000085800)
000000c000085678:  0000000000000000  000000c000085748 
000000c000085688:  0000561e2a60fba5 <runtime.gopanic+293>  000000c000000f00 
000000c000085698:  0000561e2a60dfdd <runtime.panicmem+93>  000000c000085758 
000000c0000856a8:  000000c0000856d8  0000000000000000 
000000c0000856b8:  000000c000000180  0000000000000004 
000000c0000856c8:  0000000000004000  000000c000000180 
000000c0000856d8:  0000000000002000  000000c000000f00 
000000c0000856e8:  0000000000000001  0000000000000000 
000000c0000856f8:  00007f8299cecd48  000000c000085750 
000000c000085708:  000000c000000f20  0000000000000000 
000000c000085718:  0000561e2b2a8800  0000561e2b952960 
000000c000085728:  0000000000000000  0000000000000000 
000000c000085738:  0000000000000000  0000000000000000 
000000c000085748:  000000c000085768  0000561e2a60dfdd <runtime.panicmem+93> 
000000c000085758:  0000561e2b2a8800  0000561e2b952960 
000000c000085768:  000000c0000857a0  0000561e2a627c85 <runtime.sigpanic+389> 
000000c000085778: <0000561e2b9feb10  0000561e2a6130a6 <runtime.gopark+230> 
000000c000085788:  00007f82c0b5866c  00007f82999e9b74 
000000c000085798:  000000c000000f00  0000000000000000 
000000c0000857a8: !0000000000000000 >00007f82c0b9c400 
000000c0000857b8:  00007f82c0b57c69  0000000000000000 
000000c0000857c8:  0000000000000001  0000561e2a6489e1 <runtime.goexit+1> 
000000c0000857d8:  000000c0000441c0  00007f82c0b9c400 
000000c0000857e8:  00007f82c0b58792  00007f82c0b5b352 
000000c0000857f8:  00007f82c0b9c400 
fatal error: unknown caller pc
runtime stack:
runtime.throw(0x561e2b079485, 0x11)
	/usr/lib/go/src/runtime/panic.go:1117 +0x74
runtime.gentraceback(0x561e2a60dfdd, 0xc000085758, 0x0, 0xc000000f00, 0x0, 0x0, 0x7fffffff, 0x7f8299a3fa10, 0x0, 0x0, ...)
	/usr/lib/go/src/runtime/traceback.go:261 +0x1a56
runtime.addOneOpenDeferFrame.func1()
	/usr/lib/go/src/runtime/panic.go:717 +0x93
runtime.systemstack(0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:379 +0x63
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1246
goroutine 3 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:339 fp=0xc000085650 sp=0xc000085648 pc=0x561e2a646ba0
runtime.addOneOpenDeferFrame(0xc000000f00, 0x561e2a60dfdd, 0xc000085758)
	/usr/lib/go/src/runtime/panic.go:716 +0x7d fp=0xc000085690 sp=0xc000085650 pc=0x561e2a60f01d
panic(0x561e2b2a8800, 0x561e2b952960)
	/usr/lib/go/src/runtime/panic.go:925 +0x125 fp=0xc000085758 sp=0xc000085690 pc=0x561e2a60fba5
runtime.panicmem()
	/usr/lib/go/src/runtime/panic.go:212 +0x5d fp=0xc000085778 sp=0xc000085758 pc=0x561e2a60dfdd
runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc000085778, fp:0xc0000857b0} stack=[0xc000085000,0xc000085800)
000000c000085678:  0000000000000000  000000c000085748 
000000c000085688:  0000561e2a60fba5 <runtime.gopanic+293>  000000c000000f00 
000000c000085698:  0000561e2a60dfdd <runtime.panicmem+93>  000000c000085758 
000000c0000856a8:  000000c0000856d8  0000000000000000 
000000c0000856b8:  000000c000000180  0000000000000004 
000000c0000856c8:  0000000000004000  000000c000000180 
000000c0000856d8:  0000000000002000  000000c000000f00 
000000c0000856e8:  0000000000000001  0000000000000000 
000000c0000856f8:  00007f8299cecd48  000000c000085750 
000000c000085708:  000000c000000f20  0000000000000000 
000000c000085718:  0000561e2b2a8800  0000561e2b952960 
000000c000085728:  0000000000000000  0000000000000000 
000000c000085738:  0000000000000000  0000000000000000 
000000c000085748:  000000c000085768  0000561e2a60dfdd <runtime.panicmem+93> 
000000c000085758:  0000561e2b2a8800  0000561e2b952960 
000000c000085768:  000000c0000857a0  0000561e2a627c85 <runtime.sigpanic+389> 
000000c000085778: <0000561e2b9feb10  0000561e2a6130a6 <runtime.gopark+230> 
000000c000085788:  00007f82c0b5866c  00007f82999e9b74 
000000c000085798:  000000c000000f00  0000000000000000 
000000c0000857a8: !0000000000000000 >00007f82c0b9c400 
000000c0000857b8:  00007f82c0b57c69  0000000000000000 
000000c0000857c8:  0000000000000001  0000561e2a6489e1 <runtime.goexit+1> 
000000c0000857d8:  000000c0000441c0  00007f82c0b9c400 
000000c0000857e8:  00007f82c0b58792  00007f82c0b5b352 
000000c0000857f8:  00007f82c0b9c400 
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:734 +0x185 fp=0xc0000857b0 sp=0xc000085778 pc=0x561e2a627c85
created by runtime.gcenable
	/usr/lib/go/src/runtime/mgc.go:217 +0x5e
goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0xf7, 0x1, 0x33b, 0xc00079f9d8, 0x1000004, 0x0, 0x0, 0x3, 0x0, 0xc00079fa28)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc00003a7b0, 0x6, 0x6, 0x561e2a5ec33d)
	/usr/lib/go/src/os/wait_waitid.go:32 +0x9e
os.(*Process).wait(0xc00003a7b0, 0x8, 0x561e2b3d27d0, 0x561e2b3d27d8)
	/usr/lib/go/src/os/exec_unix.go:22 +0x3b
os.(*Process).Wait(...)
	/usr/lib/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0xc000172000, 0x0, 0x0)
	/usr/lib/go/src/os/exec/exec.go:507 +0x65
os/exec.(*Cmd).Run(0xc000172000, 0x5, 0x561e2b07ee25)
	/usr/lib/go/src/os/exec/exec.go:341 +0x65
github.com/containers/buildah/chroot.runUsingChrootExecMain()
	/home/buildozer/aports/testing/buildah/src/buildah-1.19.8/chroot/run.go:798 +0x113a
github.com/containers/storage/pkg/reexec.Init(...)
	/home/buildozer/aports/testing/buildah/src/buildah-1.19.8/vendor/github.com/containers/storage/pkg/reexec/reexec.go:26
github.com/containers/buildah.InitReexec(...)
	/home/buildozer/aports/testing/buildah/src/buildah-1.19.8/util.go:27
main.main()
	/home/buildozer/aports/testing/buildah/src/buildah-1.19.8/cmd/buildah/main.go:214 +0x2b0
subprocess exited with status 2

```

I notice some commentary in https://github.com/golang/go/issues/36287 and https://github.com/golang/go/issues/44096 suggests this might be a golang bug around the use of signals. I do not know about the buildah code, but wonder if any in the community has seen such an error condition, or has ideas of a possible cause and/or workaround?

**Describe the results you expected:**

Success

**Output of `rpm -q buildah` or `apt list buildah`:**

```
I use alpine
```

**Output of `buildah version`:**

```
> docker run --entrypoint=buildah --rm -it registry.freedesktop.org/mupuf/valve-infra/gitlab-job-runner   version
Version:         1.19.8
Go Version:      go1.16
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.10.2
Git Commit:      1.19.8
Built:           Mon Mar  8 23:44:01 2021
OS/Arch:         linux/amd64
```

**Output of `uname -a`:**

```
Linux runner-eejagj3m-project-9359-concurrent-0 5.11.10-arch1-1 #1 SMP PREEMPT Fri, 26 Mar 2021 00:11:29 +0000 x86_64 Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by TomSweeneyRedHat** [comment]
@charlie-ht thanks for the report.  This is a new one to me, looks like things failed very easy in the run trying to get the runtime.  Is this something that happened once,  or is it very repeatable in your environment?

**Comment by charlie-ht** [comment]
@TomSweeneyRedHat It's a funny one indeed :-) -- I have only seen it the once so far, that's among probably 100-200 runs I'd guesstimate.

I'd be happy to run this job using any special configuration of Go or some other patches / flags that might add more information to the report, to my eyes it doesn't look super helpful for the devs right now.

**Comment by TomSweeneyRedHat** [comment]
@charlie-ht doing `buildah --debug ...` would probably be most helpful to start.

**Comment by charlie-ht** [comment]
I'll run with this and report back if I hit it again, thank you.

**Comment by rhatdan** [comment]
This definitely looks like golang.  I don't think there is anything specific about buildah other then execing into a chroot.

**Comment by charlie-ht** [comment]
Makes sense to me.

Just to update, not seen this since, and I've been hammering it with --debug logging enabled. So it seems rare indeed. Feel free to close if it's deemed out-of-scope. If I do manage to see it again, seems to me like should take it to golang :-)

**Comment by charlie-ht** [comment]
I haven't seen this issue since I first reported it, so I will close for now.
