### ISSUE TITLE
buildah panics on Fedora rawhide

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3758]
Reported by the multiarch team on [gitlab](https://gitlab.com/cki-project/kernel-tests/-/issues/622#note_826190324) (which seems to be down atm):
```
    podman version 4.0.0-rc1
    Podman debug info:
    host:
      arch: amd64
      buildahVersion: 1.23.1

....

         # # podman create --name wfhqPRTC606E18GnT9y0ImdJaDstzd quay.io/libpod/testimage:20210610 /bin/true
         # 7b032b412591530aed2a3aa8e60fef374d2db7957151bd9e38c18010e21d27a2
         # panic: runtime error: invalid memory address or nil pointer dereference
         # [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fabcb10d57c]
         # 
         # goroutine 1 [running]:
         # panic({0x7fabcbe1d000, 0x7fabcc5acae0})
         # 	/usr/lib/golang/src/runtime/panic.go:941 +0x397 fp=0xc0005f7d80 sp=0xc0005f7cc0 pc=0x7fabcb132ff7
         # runtime.panicmem(...)
         # 	/usr/lib/golang/src/runtime/panic.go:220
         # runtime.sigpanic()
         # 	/usr/lib/golang/src/runtime/signal_unix.go:797 +0x336 fp=0xc0005f7dd0 sp=0xc0005f7d80 pc=0x7fabcb1497b6
         # runtime.mapiternext(0xc0001ec5a0?)
         # 	/usr/lib/golang/src/runtime/map.go:870 +0x1c fp=0xc0005f7e40 sp=0xc0005f7dd0 pc=0x7fabcb10d57c
         # reflect.mapiternext(0xc000368d20?)
         # 	/usr/lib/golang/src/runtime/map.go:1378 +0x19 fp=0xc0005f7e58 sp=0xc0005f7e40 pc=0x7fabcb15e339
         # github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x7fabca93b5b8?)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32 fp=0xc0005f7e80 sp=0xc0005f7e58 pc=0x7fabcb514ab2
         # github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000596a20, 0xc0000ebc70, 0xc000095680)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_map.go:297 +0x31a fp=0xc0005f7ff0 sp=0xc0005f7e80 pc=0x7fabcb5548ba
         # github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000597560, 0x7fabcbd72cb7?, 0xc000095680)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc0005f8068 sp=0xc0005f7ff0 pc=0x7fabcb561f56
         # github.com/json-iterator/go.(*structEncoder).Encode(0xc000597650, 0x8a007fabca93b5b8?, 0xc000095680)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc0005f8150 sp=0xc0005f8068 pc=0x7fabcb562965
         # github.com/json-iterator/go.(*OptionalEncoder).Encode(0x7fabcbe4ce80?, 0xc0005f8228?, 0xc0005f8248?)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_optional.go:70 +0xa4 fp=0xc0005f81a0 sp=0xc0005f8150 pc=0x7fabcb559b24
         # github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0005cb170, 0xc0001428c0, 0xc000095680)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_slice.go:38 +0x2bd fp=0xc0005f8258 sp=0xc0005f81a0 pc=0x7fabcb55a57d
         # github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000328dc0?, 0x0?, 0x0?)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect_optional.go:70 +0xa4 fp=0xc0005f82a8 sp=0xc0005f8258 pc=0x7fabcb559b24
         # github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0003ba290, 0xc0001428c0, 0xc000258c90?)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect.go:219 +0x82 fp=0xc0005f82e0 sp=0xc0005f82a8 pc=0x7fabcb54cac2
         # github.com/json-iterator/go.(*Stream).WriteVal(0xc000095680, {0x7fabcbd90d60, 0xc0001428c0})
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc0005f8350 sp=0xc0005f82e0 pc=0x7fabcb54bdd8
         # github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000328dc0, {0x7fabcbd90d60, 0xc0001428c0})
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/json-iterator/go/config.go:299 +0xc9 fp=0xc0005f83e8 sp=0xc0005f8350 pc=0x7fabcb542ee9
         # github.com/containers/storage.(*layerStore).saveLayers(0xc000142870)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/layers.go:484 +0x135 fp=0xc0005f84c8 sp=0xc0005f83e8 pc=0x7fabcb881535
         # github.com/containers/storage.(*layerStore).Save(0xc000142870)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/layers.go:467 +0xc5 fp=0xc0005f8538 sp=0xc0005f84c8 pc=0x7fabcb881285
         # github.com/containers/storage.(*layerStore).Put(0xc000142870, {0x0, 0x0}, 0xc000212160, {0x0, 0x0, 0x10?}, {0xc0005ec810, 0x2f}, 0x0, ...)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/layers.go:817 +0x155b fp=0xc0005f8928 sp=0xc0005f8538 pc=0x7fabcb8849fb
         # github.com/containers/storage.(*layerStore).CreateWithFlags(...)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/layers.go:830
         # github.com/containers/storage.(*layerStore).Create(0xa?, {0x0?, 0x0?}, 0x0?, {0x0?, 0x0?, 0x0?}, {0xc0005ec810?, 0x0?}, 0x0, ...)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/layers.go:835 +0x65 fp=0xc0005f89b0 sp=0xc0005f8928 pc=0x7fabcb884fe5
         # github.com/containers/storage.(*store).CreateContainer(0xc0000eac60, {0x0, 0x0}, {0xc000081850, 0x1, 0x1}, {0xc0001f8ec0, 0x40}, {0x0, 0x0}, ...)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/containers/storage/store.go:1390 +0x1383 fp=0xc0005f8f38 sp=0xc0005f89b0 pc=0x7fabcb8974e3
         # github.com/containers/buildah.newBuilder({_, _}, {_, _}, {0x0, {0x7ffe53596121, 0x21}, {0x0, 0x0}, 0x2, ...})
         # 	/builddir/build/BUILD/buildah-1.23.1/_build/src/github.com/containers/buildah/new.go:224 +0x1183 fp=0xc0005f9658 sp=0xc0005f8f38 pc=0x7fabcba9f6c3
         # github.com/containers/buildah.NewBuilder({_, _}, {_, _}, {0x0, {0x7ffe53596121, 0x21}, {0x0, 0x0}, 0x2, ...})
         # 	/builddir/build/BUILD/buildah-1.23.1/_build/src/github.com/containers/buildah/buildah.go:366 +0xe5 fp=0xc0005f97e0 sp=0xc0005f9658 pc=0x7fabcba86ea5
         # main.fromCmd(0xc00069fd48?, {0xc0001e4c60?, 0x1, 0x1}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
         # 	/builddir/build/BUILD/buildah-1.23.1/_build/src/github.com/containers/buildah/cmd/buildah/from.go:312 +0xc8f fp=0xc0005f9ca8 sp=0xc0005f97e0 pc=0x7fabcbb4284f
         # main.init.6.func1(0xc00037bb80?, {0xc0001e4c60?, 0x1?, 0x1?})
         # 	/builddir/build/BUILD/buildah-1.23.1/_build/src/github.com/containers/buildah/cmd/buildah/from.go:56 +0xbc fp=0xc0005f9d70 sp=0xc0005f9ca8 pc=0x7fabcbb4093c
         # github.com/spf13/cobra.(*Command).execute(0xc00037bb80, {0xc0001e4c30, 0x1, 0x1})
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/spf13/cobra/command.go:856 +0x67c fp=0xc0005f9e48 sp=0xc0005f9d70 pc=0x7fabcbae721c
         # github.com/spf13/cobra.(*Command).ExecuteC(0x7fabcc5bfc00)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/spf13/cobra/command.go:974 +0x3b4 fp=0xc0005f9f00 sp=0xc0005f9e48 pc=0x7fabcbae7894
         # github.com/spf13/cobra.(*Command).Execute(...)
         # 	/builddir/build/BUILD/buildah-1.23.1/src/github.com/spf13/cobra/command.go:902
         # main.main()
         # 	/builddir/build/BUILD/buildah-1.23.1/_build/src/github.com/containers/buildah/cmd/buildah/main.go:224 +0x99 fp=0xc0005f9f80 sp=0xc0005f9f00 pc=0x7fabcbb48279
         # runtime.main()
         # 	/usr/lib/golang/src/runtime/proc.go:255 +0x227 fp=0xc0005f9fe0 sp=0xc0005f9f80 pc=0x7fabcb135b87
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005f9fe8 sp=0xc0005f9fe0 pc=0x7fabcb164b01
         # 
         # goroutine 2 [force gc (idle)]:
         # runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006afb0 sp=0xc00006af90 pc=0x7fabcb135f56
         # runtime.goparkunlock(...)
         # 	/usr/lib/golang/src/runtime/proc.go:372
         # runtime.forcegchelper()
         # 	/usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc00006afe0 sp=0xc00006afb0 pc=0x7fabcb135ded
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006afe8 sp=0xc00006afe0 pc=0x7fabcb164b01
         # created by runtime.init.7
         # 	/usr/lib/golang/src/runtime/proc.go:294 +0x25
         # 
         # goroutine 3 [GC sweep wait]:
         # runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006b790 sp=0xc00006b770 pc=0x7fabcb135f56
         # runtime.goparkunlock(...)
         # 	/usr/lib/golang/src/runtime/proc.go:372
         # runtime.bgsweep(0x0?)
         # 	/usr/lib/golang/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc00006b7c8 sp=0xc00006b790 pc=0x7fabcb1215b7
         # runtime.gcenable.func1()
         # 	/usr/lib/golang/src/runtime/mgc.go:177 +0x26 fp=0xc00006b7e0 sp=0xc00006b7c8 pc=0x7fabcb117266
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006b7e8 sp=0xc00006b7e0 pc=0x7fabcb164b01
         # created by runtime.gcenable
         # 	/usr/lib/golang/src/runtime/mgc.go:177 +0x6b
         # 
         # goroutine 4 [sleep]:
         # runtime.gopark(0xc00009e000?, 0x23b4ae10299?, 0x0?, 0x0?, 0x7fabcbf5af90?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006bee0 sp=0xc00006bec0 pc=0x7fabcb135f56
         # runtime.goparkunlock(...)
         # 	/usr/lib/golang/src/runtime/proc.go:372
         # runtime.scavengeSleep(0x3b9aca00)
         # 	/usr/lib/golang/src/runtime/mgcscavenge.go:247 +0x9f fp=0xc00006bf30 sp=0xc00006bee0 pc=0x7fabcb11f0df
         # runtime.bgscavenge(0x0?)
         # 	/usr/lib/golang/src/runtime/mgcscavenge.go:387 +0x1af fp=0xc00006bfc8 sp=0xc00006bf30 pc=0x7fabcb11f30f
         # runtime.gcenable.func2()
         # 	/usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc00006bfe0 sp=0xc00006bfc8 pc=0x7fabcb117206
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x7fabcb164b01
         # created by runtime.gcenable
         # 	/usr/lib/golang/src/runtime/mgc.go:178 +0xaa
         # 
         # goroutine 5 [finalizer wait]:
         # runtime.gopark(0x0?, 0x7fabcbf5ae38?, 0x10?, 0x20?, 0x1000000010?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00007fe30 sp=0xc00007fe10 pc=0x7fabcb135f56
         # runtime.goparkunlock(...)
         # 	/usr/lib/golang/src/runtime/proc.go:372
         # runtime.runfinq()
         # 	/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc00007ffe0 sp=0xc00007fe30 pc=0x7fabcb1162f3
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00007ffe8 sp=0xc00007ffe0 pc=0x7fabcb164b01
         # created by runtime.createfing
         # 	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45
         # 
         # goroutine 6 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fbe79?, 0x3?, 0xdb?, 0xa5?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006c758 sp=0xc00006c738 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006c7e0 sp=0xc00006c758 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 18 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fb79c?, 0x3?, 0xc5?, 0x3b?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000066758 sp=0xc000066738 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000667e0 sp=0xc000066758 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 34 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fbe3f?, 0x3?, 0x8f?, 0xe8?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000588758 sp=0xc000588738 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0005887e0 sp=0xc000588758 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005887e8 sp=0xc0005887e0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 19 [GC worker (idle)]:
         # runtime.gopark(0x7fabcc6657a0?, 0x1?, 0xaf?, 0x4a?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000066f58 sp=0xc000066f38 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000066fe0 sp=0xc000066f58 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 35 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fa1d1?, 0x3?, 0x8f?, 0x9b?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000588f58 sp=0xc000588f38 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000588fe0 sp=0xc000588f58 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000588fe8 sp=0xc000588fe0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 7 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fc19c?, 0x0?, 0x0?, 0x0?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006cf58 sp=0xc00006cf38 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006cfe0 sp=0xc00006cf58 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 20 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fb770?, 0x3?, 0x26?, 0x4c?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000067758 sp=0xc000067738 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000677e0 sp=0xc000067758 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000677e8 sp=0xc0000677e0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
         # 
         # goroutine 8 [GC worker (idle)]:
         # runtime.gopark(0x23b0d5fd3f2?, 0x1?, 0xe4?, 0x81?, 0x0?)
         # 	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00006d758 sp=0xc00006d738 pc=0x7fabcb135f56
         # runtime.gcBgMarkWorker()
         # 	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006d7e0 sp=0xc00006d758 pc=0x7fabcb119385
         # runtime.goexit()
         # 	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006d7e8 sp=0xc00006d7e0 pc=0x7fabcb164b01
         # created by runtime.gcBgMarkStartWorkers
         # 	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25
```
This is on a completely broken system, one on which almost every test fails with:
```
        # Error: plugin type="bridge" failed (add): cni plugin bridge failed: running [/usr/sbin/iptables -t nat -C CNI-a5767c234fdd0783be1e797e -d 10.88.0.61/16 -j ACCEPT -m comment --comment name: "podman" id: "2e5b85f0b88f8f1c49ec907899401d38f809e0e5fcd7a84b80b4449d6a244955" --wait]: exit status 2: iptables v1.8.7 (nf_tables): Couldn't load match `comment':No such file or directory
```
(this is a known problem, and a constant source of test failures in their setup, but not one which I feel we need to look into. I merely add this in case it is relevant context).

**Comment by edsantiago** [comment]
Yep, confirmed:
```console
# buildah from quay.io/libpod/testimage:20210610
[crash]
```
buildah-1.23.1-2.fc36.x86_64

5.17.0-0.rc0.20220112gitdaadb3bd0e8d.63.fc36.x86_64

**Comment by rhatdan** [comment]
Is this still happening with podman 4.0 RC3? Which includes a new version of Buildah?

**Comment by edsantiago** [comment]
Podman has nothing to do with it. I apologize for the initial false alarm, it was due to me not looking closely enough at the test source code. It's 100% buildah, 100% reproducible even on a system without podman installed.

**Comment by rhatdan** [comment]
Ok with buildah 1.24?
Can you give me a reproducer?

**Comment by edsantiago** [comment]
I did, see above. (1.23, not 1.24)

**Comment by edsantiago** [comment]
Rawhide, not f35.

With `buildah-1.24.0-4.fc36.x86_64` and `containers-common-1-46.fc36.noarch` from koji, the crash is gone. But that version of buildah isn't even in `updates-testing` yet.

**Comment by TomSweeneyRedHat** [comment]
I'm not sure what's going on, probably need a c/storage heavy to look.  The failure is happening as @edsantiago noted from this command:

`# buildah from quay.io/libpod/testimage:20210610`

And the path through buildah is pretty quick.  The from command is called and it asks c/storage to get the layers of the image:

Calling saveLayers() in c/storage/layers.go
https://github.com/containers/buildah/blob/release-1.23/vendor/github.com/containers/storage/layers.go#L473

and then failing at: 
https://github.com/containers/buildah/blob/release-1.23/vendor/github.com/containers/storage/layers.go#L484
which is simply doing:

`jldata, err := json.Marshal(&r.layers)`

Deep inside that code, it's going unhinged, I'm assuming due to finding a nil variable somewhere that it was not expecting.

How was/is that test image created?  Could it simply be a version skew between that image and what's in 1.23.1?

**Comment by edsantiago** [comment]
testimage is created by https://github.com/containers/podman/blob/905d31ddd358bb6c40082c391102bbf92a04fad6/test/system/build-testimage

**Comment by TomSweeneyRedHat** [comment]
@edsantiago and the image is built as part of the test run rather than something that's done in advance and set aside?

Also, it looks like you're using buildah to create the image, and then you tag it using podman.  I wonder if podman that is called is using a different c/storage?  Could you use `buildah tag` instead?

**Comment by edsantiago** [comment]
@TomSweeneyRedHat the `:20210610` in the image means "this was built on 2021-06-10". Even if I had a strong desire to build a new one today, it would not help with all the existing branches that use the `:20210610` image. This must be fixed in buildah.

**Comment by TomSweeneyRedHat** [comment]
And it looks like the mystery deepens.  This works in 1.23.2:

```
# ./bin/buildah from quay.io/libpod/testimage:20210610
Trying to pull quay.io/libpod/testimage:20210610...
Getting image source signatures
Copying blob 9afcdfe780b4 done  
Copying config 9f9ec7f2fd done  
Writing manifest to image destination
Storing signatures
testimage-working-container

# ./bin/buildah -v
buildah version 1.23.2 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)

```

**Comment by edsantiago** [comment]
@TomSweeneyRedHat see above, @nalind has already opened #3763 to address

**Comment by TomSweeneyRedHat** [comment]
and as usual, @nalind figured it out!  Thanks Nalin, nice catch.

**Comment by edsantiago** [comment]
Weird: #3763 merged but didn't autoclose this one despite the `Fixes`

**Comment by TomSweeneyRedHat** [comment]
@nalind @rhatdan @edsantiago @jnovy Nalin just spun up release v1.23.3 with this fix.  This issue is present in RHEL 8.5.0.2.  Should we vendor buildah v1.23.3 into Podman v3.4..2-rhel then bump Podman and Buildah both in  RHEL 8.5.0.3?  How severe is this issue?

**Comment by edsantiago** [comment]
>Should we vendor buildah v1.23.3 into Podman [...]

Has anyone reproduced the problem using podman? AFAIK it only happens with buildah; I've never seen it in `podman build` even though all the podman tests use that same testimage.

I cannot comment on any of your other questions, sorry.

**Comment by nalind** [comment]
Check the version of `github.com/modern-go/reflect2` in that version of podman's `vendor/modules.txt` file.  If it's already using v1.0.2, or if we're building podman with a version of Go before 1.18, I don't think this problem is going to crop up there.

**Comment by TomSweeneyRedHat** [comment]
@nalind that branch of Podman has reflect2 v1.0.1 there, but I thnk it's using GoLang 1.16 to do the builds.  @cevich can you verify which version of Go is run against the Podman v3.4.2-rhel branch please?

**Comment by cevich** [comment]
Yes, we're running `golang-1.16.6-2.fc34` and `golang-1.15.14-2.fc33`.

**Comment by TomSweeneyRedHat** [comment]
OK, so we should be good for Podman v4.0 then given the above, but we probably ought to bump reflect2 up to v1.0.2 in the main branch of Podman so we don't run into this in the future.
