### ISSUE TITLE
buildah run: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by portestos** [containers/buildah#4251]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Since around one or two weeks rootful `buildah run` fails after execution.
This behaviour seems to be independent of the used container image.
The failure seems to happen after the process in the container has completed and exits.
This issue doesn't happen with rootless buildah containers.

**Steps to reproduce the issue:**

```
$ sudo buildah from docker.io/library/alpine
alpine-working-container
$ sudo buildah run alpine-working-container echo test
test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c pc=0x5593e941a2e2]

goroutine 1 [running]:
panic({0x5593e9ef5040, 0x5593ea72fa80})
	/usr/lib/golang/src/runtime/panic.go:941 +0x397 fp=0xc00061dc80 sp=0xc00061dbc0 pc=0x5593e90e5db7
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:220
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:818 +0x336 fp=0xc00061dcd0 sp=0xc00061dc80 pc=0x5593e90fc8b6
github.com/sirupsen/logrus.(*Logger).Logf(0xc0001d4378?, 0x18?, {0x5593e9c2250f?, 0x18?}, {0xc00061dd80?, 0x0?, 0x0?})
	/builddir/build/BUILD/buildah-1.27.0/src/github.com/sirupsen/logrus/logger.go:152 +0x22 fp=0xc00061dd20 sp=0xc00061dcd0 pc=0x5593e941a2e2
github.com/sirupsen/logrus.(*Logger).Errorf(...)
	/builddir/build/BUILD/buildah-1.27.0/src/github.com/sirupsen/logrus/logger.go:186
github.com/containers/buildah.(*Builder).runConfigureNetwork.func1()
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/run_linux.go:579 +0x117 fp=0xc00061dde0 sp=0xc00061dd20 pc=0x5593e9b88f97
runtime.deferreturn()
	/usr/lib/golang/src/runtime/panic.go:436 +0x33 fp=0xc00061de20 sp=0xc00061dde0 pc=0x5593e90e4ed3
github.com/containers/buildah.(*Builder).runUsingRuntimeSubproc(_, _, {0x0, {0x0, 0x0}, 0x0, {0x5593e9bffd89, 0x4}, {0x5593ea7ee250, 0x0, ...}, ...}, ...)
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/run_common.go:1235 +0x14ce fp=0xc00061e790 sp=0xc00061de20 pc=0x5593e9b7b0ae
github.com/containers/buildah.(*Builder).Run(_, {_, _, _}, {0x0, {0x0, 0x0}, 0x0, {0x5593e9bffd89, 0x4}, ...})
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/run_linux.go:358 +0x2c74 fp=0xc00061f600 sp=0xc00061e790 pc=0x5593e9b856b4
main.runCmd(_, {_, _, _}, {0x0, {0x5593ea7ee250, 0x0, 0x0}, {0x5593ea7ee250, 0x0, ...}, ...})
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/cmd/buildah/run.go:171 +0x778 fp=0xc00061fc48 sp=0xc00061f600 pc=0x5593e9bf38f8
main.init.21.func1(0xc0002ff400?, {0xc000316720?, 0x3?, 0x3?})
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/cmd/buildah/run.go:52 +0x9b fp=0xc00061fd70 sp=0xc00061fc48 pc=0x5593e9bf313b
github.com/spf13/cobra.(*Command).execute(0xc0002ff400, {0xc0003166f0, 0x3, 0x3})
	/builddir/build/BUILD/buildah-1.27.0/src/github.com/spf13/cobra/command.go:872 +0x694 fp=0xc00061fe48 sp=0xc00061fd70 pc=0x5593e9b25ab4
github.com/spf13/cobra.(*Command).ExecuteC(0x5593ea7435a0)
	/builddir/build/BUILD/buildah-1.27.0/src/github.com/spf13/cobra/command.go:990 +0x3b4 fp=0xc00061ff00 sp=0xc00061fe48 pc=0x5593e9b26134
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/buildah-1.27.0/src/github.com/spf13/cobra/command.go:918
main.main()
	/builddir/build/BUILD/buildah-1.27.0/_build/src/github.com/containers/buildah/cmd/buildah/main.go:234 +0x71 fp=0xc00061ff80 sp=0xc00061ff00 pc=0x5593e9be7bd1
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x213 fp=0xc00061ffe0 sp=0xc00061ff80 pc=0x5593e90e8933
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x5593e9118041

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000062fb0 sp=0xc000062f90 pc=0x5593e90e8cf6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:301 +0xad fp=0xc000062fe0 sp=0xc000062fb0 pc=0x5593e90e8b8d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x5593e9118041
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:289 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000063790 sp=0xc000063770 pc=0x5593e90e8cf6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.bgsweep(0x0?)
	/usr/lib/golang/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000637c8 sp=0xc000063790 pc=0x5593e90d3d17
runtime.gcenable.func1()
	/usr/lib/golang/src/runtime/mgc.go:177 +0x26 fp=0xc0000637e0 sp=0xc0000637c8 pc=0x5593e90c9886
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x5593e9118041
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:177 +0x6b

goroutine 4 [sleep]:
runtime.gopark(0xc00003c050?, 0xdb1bfa8129b?, 0x0?, 0x0?, 0x5593ea053190?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000063ed0 sp=0xc000063eb0 pc=0x5593e90e8cf6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.scavengeSleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/mgcscavenge.go:248 +0x9f fp=0xc000063f20 sp=0xc000063ed0 pc=0x5593e90d17ff
runtime.bgscavenge(0x0?)
	/usr/lib/golang/src/runtime/mgcscavenge.go:394 +0x1af fp=0xc000063fc8 sp=0xc000063f20 pc=0x5593e90d1a2f
runtime.gcenable.func2()
	/usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc000063fe0 sp=0xc000063fc8 pc=0x5593e90c9826
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x5593e9118041
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:178 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0xc000003860?, 0x0?, 0x70?, 0x27?, 0x5593e90f58d1?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000062630 sp=0xc000062610 pc=0x5593e90e8cf6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000627e0 sp=0xc000062630 pc=0x5593e90c8933
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000627e8 sp=0xc0000627e0 pc=0x5593e9118041
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0xdb18369874f?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000064758 sp=0xc000064738 pc=0x5593e90e8cf6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000647e0 sp=0xc000064758 pc=0x5593e90cb9a5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x5593e9118041
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xdb183677100?, 0x1?, 0xc7?, 0x50?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000064f58 sp=0xc000064f38 pc=0x5593e90e8cf6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000064fe0 sp=0xc000064f58 pc=0x5593e90cb9a5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x5593e9118041
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0xdb183696e98?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00005e758 sp=0xc00005e738 pc=0x5593e90e8cf6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00005e7e0 sp=0xc00005e758 pc=0x5593e90cb9a5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x5593e9118041
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xdb1836972e5?, 0x3?, 0x3c?, 0x3f?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000588758 sp=0xc000588738 pc=0x5593e90e8cf6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0005887e0 sp=0xc000588758 pc=0x5593e90cb9a5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005887e8 sp=0xc0005887e0 pc=0x5593e9118041
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 31 [select, locked to thread]:
runtime.gopark(0xc000588fa8?, 0x2?, 0x1?, 0x0?, 0xc000588fa4?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000588e18 sp=0xc000588df8 pc=0x5593e90e8cf6
runtime.selectgo(0xc000588fa8, 0xc000588fa0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:328 +0x772 fp=0xc000588f58 sp=0xc000588e18 pc=0x5593e90f8a12
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:973 +0x1bb fp=0xc000588fe0 sp=0xc000588f58 pc=0x5593e90fcdfb
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000588fe8 sp=0xc000588fe0 pc=0x5593e9118041
created by runtime.ensureSigM
	/usr/lib/golang/src/runtime/signal_unix.go:956 +0xbd

goroutine 79 [syscall]:
runtime.notetsleepg(0x5593e90efbe5?, 0xc00051cde0?)
	/usr/lib/golang/src/runtime/lock_futex.go:235 +0x34 fp=0xc0000607a0 sp=0xc000060768 pc=0x5593e90b9eb4
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:151 +0x2f fp=0xc0000607c0 sp=0xc0000607a0 pc=0x5593e91144ef
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x19 fp=0xc0000607e0 sp=0xc0000607c0 pc=0x5593e9434699
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x5593e9118041
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x2a
Abgebrochen
$ echo $?
134
```

**Describe the results you received:**

See the above output.

**Describe the results you expected:**

```
$ sudo buildah run alpine-working-container echo test
test
$ echo $?
0
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.27.0-1.fc36.x86_64
```

**Output of `buildah version`:**

```
Version:         1.27.0
Go Version:      go1.18.4
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.22.0
Git Commit:      
Built:           Tue Aug  9 04:26:49 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 16:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 36 (Thirty Six)
NAME="Fedora Linux"
VERSION="36.20220914.0 (Silverblue)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36.20220914.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='36.20220914.0'
Fedora release 36 (Thirty Six)
Fedora release 36 (Thirty Six)
```

**Output of `uname -a`:**

```
Linux thinkpad 5.19.8-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 8 19:02:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

Doesn't exist

**Other info:**

`podman build` also shows an error after executing the first `RUN` instruction:

```
[...]
Executing busybox-1.35.0-r17.trigger
Executing ca-certificates-20220614-r0.trigger
OK: 177 MiB in 105 packages
ERRO[0005] failed to cleanup network: netavark: failed to delete if podman0: Received a netlink error message Operation not supported (os error 95) 
--> 1fcced041e4
STEP 3/7: COPY files /tmp/files
--> 83b563906e0
STEP 4/7: RUN /tmp/files/run/config
--> a1eb4a6570d
[...]
```

Subsequent `RUN` instructions in the same Containerfile don't show errors.
The produced container image seems to work as expected.
This error also only shows up when executing `podman build` as root.

I already tried resetting my rootful container storage as well as the configs in `/etc/containers` and `/etc/cni` and deleting all container related directories in `/var/tmp` but none of that helped.

I upgraded from Silverblue 35 to 36 some weeks ago and there are probably some old configs left over in the writeable parts of Silverblue like `/etc` and `/var`.
I'm not aware of anyone else having this issue.

**Comment by flouthoc** [comment]
I am unable to reproduce this on my environment, actual issue could be in the teardown. Could you please update netavark and aardvark to version `v1.1.0` and try again. But I think we need to add a check for SIGSEGV.

**Comment by jheidecker** [comment]
I had this exact same issue with Silverblue 36. Looked into the [natavark version in 36](https://packages.fedoraproject.org/pkgs/netavark/netavark/). Not interested in manually installing. Rebase to 37 resolved the issue! Hope that helps.

**Comment by flouthoc** [comment]
@portestos ^ I think same should happen in your case , netavark and aardvark bumps should help here ( make sure they have same version as well )
