### ISSUE TITLE
TestCheckLUKSPassphrase: FAIL on i386

### ISSUE THREAD

**Issue by siretart** [containers/buildah#5089]
When running the testsuite on i386 (and armel, but not on 64bit platforms), I see this:

```
--- FAIL: TestCheckLUKSPassphrase (1.19s)
    --- PASS: TestCheckLUKSPassphrase/v1 (0.49s)
    --- FAIL: TestCheckLUKSPassphrase/v2 (0.70s)
        --- FAIL: TestCheckLUKSPassphrase/v2/sectorSize=512 (0.70s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 98 [running]:
testing.tRunner.func1.2({0x8478b60, 0x856142c})
	/usr/lib/go-1.21/src/testing/testing.go:1545 +0x2ab
testing.tRunner.func1()
	/usr/lib/go-1.21/src/testing/testing.go:1548 +0x43e
panic({0x8478b60, 0x856142c})
	/usr/lib/go-1.21/src/runtime/panic.go:914 +0x1ec
golang.org/x/crypto/argon2.initBlocks(0x9de0050, 0xffffffc0, 0x10)
	/<<PKGBUILDDIR>>/_build/src/golang.org/x/crypto/argon2/argon2.go:158 +0x49
golang.org/x/crypto/argon2.deriveKey(0x1, {0xa00c300, 0x40, 0x40}, {0xabf8080, 0x20, 0x20}, {0x0, 0x0, 0x0}, ...)
	/<<PKGBUILDDIR>>/_build/src/golang.org/x/crypto/argon2/argon2.go:113 +0x181
golang.org/x/crypto/argon2.Key(...)
	/<<PKGBUILDDIR>>/_build/src/golang.org/x/crypto/argon2/argon2.go:73
github.com/containers/luksy.EncryptV2({0xa29bf54, 0x2, 0x2}, {0x0, 0x0}, 0x200)
	/<<PKGBUILDDIR>>/_build/src/github.com/containers/luksy/encrypt.go:277 +0x15b6
github.com/containers/buildah/internal/mkcw.TestCheckLUKSPassphrase.func2.1(0x9dfe4b0)
	/<<PKGBUILDDIR>>/_build/src/github.com/containers/buildah/internal/mkcw/luks_test.go:44 +0xb3
testing.tRunner(0x9dfe4b0, 0x9c38e70)
	/usr/lib/go-1.21/src/testing/testing.go:1595 +0x120
created by testing.(*T).Run in goroutine 97
	/usr/lib/go-1.21/src/testing/testing.go:1648 +0x3dd
FAIL	github.com/containers/buildah/internal/mkcw	4.445s
=== RUN   TestGetTempDir

```

**Comment by siretart** [comment]
* https://buildd.debian.org/status/fetch.php?pkg=golang-github-containers-buildah&arch=armel&ver=1.32.0%2Bds1-1&stamp=1697456547&raw=0
* https://buildd.debian.org/status/fetch.php?pkg=golang-github-containers-buildah&arch=i386&ver=1.32.0%2Bds1-1&stamp=1697456137&raw=0

**Comment by flouthoc** [comment]
@nalind PTAL

**Comment by nalind** [comment]
Fixed by https://github.com/containers/luksy/pull/17, give or take Renovate pulling it in.

**Comment by siretart** [comment]
Awesome thanks, I'll update the Debian packages soon

**Comment by flouthoc** [comment]
I am closing this issue since above PR is merged.
